# Generated by Django 5.2.12 on 2026-05-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_brandconfig_accent_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("primary_color", models.CharField(max_length=7)),
                ("secondary_color", models.CharField(max_length=7)),
                ("accent_color", models.CharField(max_length=7)),
                ("background_color", models.CharField(max_length=7)),
                ("text_color", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "hero_image",
                    models.ImageField(blank=True, upload_to="landings/heroes/"),
                ),
                (
                    "cta_button_text",
                    models.CharField(default="Peça Agora", max_length=50),
                ),
                ("cta_link", models.URLField(default="/menu")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
        ),
    ]
