# Generated by Django 5.2.12 on 2026-06-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("stores", "0005_product_available_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="combination_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stores.product",
            ),
        ),
    ]
