# Generated by Django 5.2.12 on 2026-08-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_combination_details_orderitem_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_product",
        ),
    ]
