# Generated by Django 5.2.12 on 2026-05-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_cart_cartitem_cart_cart_user_or_session_exclusive_and_more"),
        ("stores", "0003_alter_product_category"),
        ("tenants", "0004_tenant_whatsapp_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombinationPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combination_type",
                    models.CharField(
                        choices=[("half_half", "Meio a Meio")], max_length=20
                    ),
                ),
                (
                    "price_calculation_method",
                    models.CharField(
                        choices=[
                            ("max_price", "Preço da Mais Cara"),
                            ("average", "Média dos Preços"),
                            ("sum_halved", "Soma/2"),
                        ],
                        default="max_price",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "combination_type",
                    models.CharField(
                        choices=[
                            ("half_half", "Meio a Meio"),
                            ("third_third", "Três Sabores"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="combination_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("cart", "product"),
                name="unique_cart_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product_key__isnull", False)),
                fields=("cart", "product_key"),
                name="unique_cart_product_key",
            ),
        ),
        migrations.AddField(
            model_name="combinationpricingrule",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.AddField(
            model_name="productcombination",
            name="base_products",
            field=models.ManyToManyField(
                limit_choices_to={"tenant": models.F("tenant")},
                related_name="combination_bases",
                to="stores.product",
            ),
        ),
        migrations.AddField(
            model_name="productcombination",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
            ),
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="combinationpricingrule",
            unique_together={("tenant", "combination_type")},
        ),
    ]
