# Generated by Django 5.2.12 on 2026-08-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_phone"),
        ("orders", "0003_remove_unique_cart_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="customers.customer",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_complement",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_neighborhood",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_reference",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Ponto de referência"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_state",
            field=models.CharField(blank=True, max_length=2, verbose_name="Estado"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_street",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Rua / Avenida"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_zip_code",
            field=models.CharField(
                blank=True, max_length=9, verbose_name="CEP de entrega"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data do pedido"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(max_length=20, verbose_name="Telefone do cliente"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("confirmed", "Confirmado"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Total"
            ),
        ),
    ]
