# Generated by Django 5.2.12 on 2026-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_combinationpricingrule_productcombination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Observações do cliente para o item", null=True
            ),
        ),
    ]
