# Generated by Django 5.2.12 on 2026-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_customer_order_delivery_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nome do cliente"
            ),
        ),
    ]
