# Generated by Django 5.2.12 on 2026-08-28 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_coupon_code_order_delivery_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="abandoned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Descartado em"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="checkout_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("delivery", "Entrega"), ("pickup", "Retirada")],
                default="delivery",
                max_length=20,
                verbose_name="Forma de recebimento",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_change_for",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Troco para"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Forma de pagamento"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="public_token",
            field=models.UUIDField(
                blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="source_cart_id",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="whatsapp_opened_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="WhatsApp aberto em"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Observações do cliente no momento do pedido",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_key",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
