# Generated by Django 5.2.12 on 2026-08-28 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_abandoned_at_order_checkout_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="public_token",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
