# Generated by Django 5.2.12 on 2026-09-01 22:16

import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def repair_carts(apps, schema_editor):
    alias = schema_editor.connection.alias
    Cart = apps.get_model("orders", "Cart")
    Item = apps.get_model("orders", "CartItem")
    Order = apps.get_model("orders", "Order")
    # Only invalid, unsubmitted cart lines are discarded; historical orders stay intact.
    affected = set()
    for item in Item.objects.using(alias).all().iterator():
        if item.quantity < 1 or not item.price.is_finite() or item.price < 0:
            affected.add(item.cart_id)
            item.delete(using=alias)
    keepers = {}
    for cart in Cart.objects.using(alias).order_by("pk").iterator():
        key = (cart.tenant_id, cart.user_id, cart.session_key)
        if key in keepers:
            keeper = keepers[key]
            affected.update([keeper, cart.pk])
            # Preserve each valid line, even when its old key equals another line.
            for item in Item.objects.using(alias).filter(cart_id=cart.pk).iterator():
                item.cart_id = keeper
                item.product_key = "legacy:" + str(item.pk)
                item.save(using=alias, update_fields=["cart", "product_key"])
            cart.delete(using=alias)
        else:
            keepers[key] = cart.pk
            cart.checkout_token = uuid.uuid4()
            cart.save(using=alias, update_fields=["checkout_token"])
    if affected:
        Order.objects.using(alias).filter(
            source_cart_id__in=affected,
            whatsapp_opened_at__isnull=True,
            abandoned_at__isnull=True,
        ).update(abandoned_at=timezone.now())

    # Flush deferred FK checks created by the data repair before the following
    # ALTER TABLE operations. Keep the entire migration atomic on PostgreSQL.
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SET CONSTRAINTS ALL IMMEDIATE")
            cursor.execute("SET CONSTRAINTS ALL DEFERRED")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_public_token"),
        ("stores", "0009_delete_deliveryzone"),
        (
            "tenants",
            "0011_alter_brandconfig_options_brandconfig_base_font_size_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="checkout_token",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(repair_carts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cart",
            name="checkout_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("tenant", "user"),
                name="unique_cart_tenant_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("tenant", "session_key"),
                name="unique_cart_tenant_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="cart_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)),
                name="cart_item_price_nonnegative",
            ),
        ),
    ]
