# Generated by Django 5.2.12 on 2026-09-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cart_checkout_token_cart_unique_cart_tenant_user_and_more'),
        ('stores', '0009_delete_deliveryzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deducted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'product'), name='unique_stock_order_product'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_reserved_positive'), models.CheckConstraint(condition=models.Q(('deducted_quantity__gte', 0)), name='stock_deducted_nonnegative')],
            },
        ),
    ]
