# Generated by Django 5.2.12 on 2026-09-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_stockreservation'),
        ('stores', '0011_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item do carrinho', 'verbose_name_plural': 'Itens do carrinho'},
        ),
        migrations.AlterModelOptions(
            name='combinationpricingrule',
            options={'verbose_name': 'Regra de preço da combinação', 'verbose_name_plural': 'Regras de preço das combinações'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item do pedido', 'verbose_name_plural': 'Itens do pedido'},
        ),
        migrations.AlterModelOptions(
            name='productcombination',
            options={'verbose_name': 'Combinação de produtos', 'verbose_name_plural': 'Combinações de produtos'},
        ),
        migrations.AlterModelOptions(
            name='stockreservation',
            options={'verbose_name': 'Reserva de estoque', 'verbose_name_plural': 'Reservas de estoque'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Observações do cliente no momento do pedido', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
