# Generated by Django 5.2.12 on 2026-10-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_fulfillment_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão de entrega/retirada'),
        ),
        migrations.AddField(
            model_name='ordernotificationsettings',
            name='allow_skip_notification',
            field=models.BooleanField(default=True, verbose_name='Permitir omitir aviso por pedido'),
        ),
        migrations.AddField(
            model_name='ordernotificationsettings',
            name='default_delivery_minutes',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='Prazo padrão de entrega (minutos)'),
        ),
        migrations.AddField(
            model_name='ordernotificationsettings',
            name='default_pickup_minutes',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Prazo padrão de retirada (minutos)'),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalhes operacionais'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('preparing', 'Em preparo'), ('ready', 'Pronto'), ('ready_for_pickup', 'Pronto para retirada'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=24, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('preparing', 'Em preparo'), ('ready', 'Pronto'), ('ready_for_pickup', 'Pronto para retirada'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], max_length=24, verbose_name='Status anterior'),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='to_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('preparing', 'Em preparo'), ('ready', 'Pronto'), ('ready_for_pickup', 'Pronto para retirada'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], max_length=24, verbose_name='Novo status'),
        ),
    ]
