# Generated by Django 5.2.12 on 2026-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_operational_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_priority',
            field=models.BooleanField(default=False, verbose_name='Prioridade na cozinha'),
        ),
    ]
