# Generated by Django 5.2.12 on 2026-10-08 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customeraddress_created_at'),
        ('orders', '0015_kitchen_priority'),
        ('tenants', '0016_tenant_whatsapp_order_number_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Agendado para'),
        ),
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_enabled', models.BooleanField(default=False)),
                ('lead_minutes', models.PositiveIntegerField(default=60)),
                ('horizon_days', models.PositiveIntegerField(default=7)),
                ('recovery_enabled', models.BooleanField(default=False)),
                ('recovery_minutes', models.PositiveIntegerField(default=60)),
                ('feedback_enabled', models.BooleanField(default=False)),
                ('feedback_minutes', models.PositiveIntegerField(default=120)),
                ('reactivation_enabled', models.BooleanField(default=False)),
                ('inactive_days', models.PositiveIntegerField(default=30)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'customer'), name='sales_consent_customer')],
            },
        ),
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_1_5')],
            },
        ),
        migrations.CreateModel(
            name='SalesMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=24)),
                ('key', models.CharField(max_length=120)),
                ('text', models.TextField(blank=True)),
                ('recipient', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='sales_message_once')],
            },
        ),
    ]
