# Generated by Django 5.2.12 on 2026-10-08 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_couponcampaign_starts_at'),
        ('customers', '0005_alter_customeraddress_created_at'),
        ('orders', '0016_order_scheduled_for_salessettings_marketingconsent_and_more'),
        ('tenants', '0016_tenant_whatsapp_order_number_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CustomerCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('segment', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='salesmessage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customercampaign'),
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reais_per_point', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('reward_points', models.PositiveIntegerField(default=100)),
                ('reward_value', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'customer'), name='crm_customer_tenant')],
            },
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=64)),
                ('stage', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'session', 'stage'), name='funnel_session_stage')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coupons.couponcampaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='loyalty_entry_key')],
            },
        ),
    ]
