# Generated by Django 5.2.12 on 2026-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="Telefone"),
        ),
    ]
