# Generated by Django 5.2.12 on 2026-08-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_verified",
            field=models.BooleanField(
                default=False, verbose_name="Telefone verificado"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data da verificação do telefone"
            ),
        ),
    ]
