# Generated by Django 5.2.12 on 2026-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_reset_legacy_phone_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
