# Generated by Django 5.2.12 on 2026-08-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        (
            "tenants",
            "0011_alter_brandconfig_options_brandconfig_base_font_size_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_tenant_admin",
            field=models.BooleanField(
                default=False, verbose_name="Administrador da loja"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="tenants.tenant",
                verbose_name="Loja",
            ),
        ),
    ]
