# Generated by Django 5.2.12 on 2026-09-01 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendingcontactchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Data e hora')),
                ('event', models.CharField(choices=[('login_succeeded', 'Login concluído'), ('login_failed', 'Falha no login'), ('logout', 'Saída da conta'), ('access_denied', 'Acesso recusado'), ('rate_limited', 'Limite de tentativas atingido'), ('registration_started', 'Cadastro iniciado'), ('account_created', 'Conta criada'), ('otp_sent', 'OTP aceito pelo provedor'), ('otp_confirmed', 'OTP confirmado'), ('otp_rejected', 'OTP recusado'), ('otp_delivery_failed', 'Falha no envio do OTP'), ('contact_requested', 'Alteração de contato solicitada'), ('contact_cancelled', 'Alteração de contato cancelada'), ('email_changed', 'E-mail alterado'), ('phone_changed', 'WhatsApp alterado'), ('password_changed', 'Senha alterada'), ('password_reset_requested', 'Recuperação de senha solicitada'), ('password_reset_failed', 'Falha na recuperação de senha'), ('token_refreshed', 'Token de acesso renovado')], db_index=True, max_length=32, verbose_name='Evento')),
                ('scope', models.CharField(choices=[('auth', 'Autenticação'), ('account', 'Conta'), ('registration', 'Cadastro'), ('contact', 'Contato'), ('dashboard', 'API do lojista')], max_length=20, verbose_name='Fluxo')),
                ('reason', models.CharField(blank=True, choices=[('', '—'), ('invalid_credentials', 'Credenciais inválidas'), ('invalid_input', 'Dados inválidos'), ('not_allowed', 'Operação não permitida'), ('rate_limit', 'Limite de envios ou tentativas'), ('cooldown', 'Intervalo entre envios'), ('attempts', 'Tentativas de OTP esgotadas'), ('expired', 'Código ou solicitação expirado'), ('delivery', 'Provedor indisponível ou envio não confirmado'), ('invalid_code', 'Código incorreto'), ('rejected', 'Solicitação inválida ou já encerrada'), ('unexpected', 'Erro interno')], max_length=24, verbose_name='Motivo')),
                ('channel', models.CharField(blank=True, choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=8, verbose_name='Canal')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID da requisição')),
                ('route', models.CharField(blank=True, max_length=120, verbose_name='Rota (sem parâmetros)')),
                ('reference', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID da solicitação OTP')),
                ('identifier_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Identificador protegido')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_security_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da sessão')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='Conta afetada')),
            ],
            options={
                'verbose_name': 'Evento de segurança',
                'verbose_name_plural': 'Eventos de segurança',
                'ordering': ['-created_at', '-pk'],
                'default_permissions': ('view',),
            },
        ),
    ]
