version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-delivery}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    dns:
      - 8.8.8.8
      - 8.8.4.4

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - appnet
    dns:
      - 8.8.8.8

  web:
    build: .
    command: /entrypoint.sh
    env_file: .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - ./:/app:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - appnet
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
    networks:
      - appnet
    restart: always
    dns:
      - 8.8.8.8

volumes:
  pgdata:
  static_volume:

networks:
  appnet:
    driver: bridge
