import {Pagination} from '../../components/Pagination';
import {useState} from 'react';
import {request} from '../../api/client';
import {useQuery} from '../../hooks/useQuery';
import {Feedback} from '../../components/Feedback';
const groups=[['Agendamentos','Permita que o cliente escolha uma data futura. A antecedência é o tempo mínimo entre a compra e o atendimento.',['scheduling_enabled','lead_minutes','horizon_days']],['Recuperação de carrinhos','Envie um lembrete após o tempo de espera para carrinhos abandonados.',['recovery_enabled','recovery_minutes']],['Avaliações','Solicite uma avaliação depois que o pedido for entregue.',['feedback_enabled','feedback_minutes']],['Reativação','Convide clientes a comprar novamente após o período sem pedidos.',['reactivation_enabled','inactive_days']]] as const;
const labels:Record<string,string>={scheduling_enabled:'Aceitar pedidos agendados',lead_minutes:'Antecedência mínima (min)',horizon_days:'Horizonte máximo (dias)',recovery_enabled:'Recuperar carrinhos',recovery_minutes:'Espera do carrinho (min)',feedback_enabled:'Pedir avaliação após entrega',feedback_minutes:'Espera após entrega (min)',reactivation_enabled:'Reativar clientes',inactive_days:'Inatividade (dias)'};
export function Sales(){
 const[pages,setPages]=useState({messages:1,feedback:1}),[size,setSize]=useState(10);const q=useQuery(()=>request(`sales/?messages_page=${pages.messages}&feedback_page=${pages.feedback}&page_size=${size}`),[pages.messages,pages.feedback,size]);const [error,setError]=useState<Error|null>(null),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 async function post(body:any){setBusy(true);setError(null);setSaved(false);try{await request('sales/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setSaved(true);q.reload();}catch(e){setError(e as Error);}finally{setBusy(false);}}
 return <><h1>Agendamento e automações</h1><p>Mensagens apenas para clientes com telefone verificado e autorização. Limite de uma tentativa por cliente a cada sete dias, entre 9h e 21h.</p><Feedback loading={q.loading} error={q.error||error}>{q.data&&<><form className="card" key={JSON.stringify(q.data.settings)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);post(Object.fromEntries(Object.entries(q.data.settings).map(([k,v])=>[k,typeof v==='boolean'?f.has(k):Number(f.get(k))])));}}>{groups.map(([title,description,keys])=><fieldset className="automation-group" key={title}><legend>{title}</legend><p>{description}</p><div className="settings-grid">{keys.filter(k=>k in q.data.settings).map(k=>{const v=q.data.settings[k];return <label className={typeof v==='boolean'?'toggle-row':'field'} key={k}>{typeof v==='boolean'?<><input name={k} type="checkbox" defaultChecked={v}/>{labels[k]}</>:<>{labels[k]}<input name={k} type="number" min={k==="horizon_days"?1:k==="inactive_days"?7:k==="recovery_minutes"?30:15} max={k==="horizon_days"?30:k==="inactive_days"?365:k==="lead_minutes"?1440:10080} defaultValue={v} required/></>}</label>;})}</div></fieldset>)}<button disabled={busy}>Salvar configurações</button>{saved&&<p role="status">Configurações salvas.</p>}</form><h2>Avaliações</h2><Pagination page={q.data.feedback_pagination?.page} pages={q.data.feedback_pagination?.pages} size={size} onPage={n=>setPages({...pages,feedback:n})} onSize={n=>{setSize(n);setPages({messages:1,feedback:1});}}/>{!q.data.feedback.length&&<p>Nenhuma avaliação recebida.</p>}{q.data.feedback.map((f:any)=><article className="card" key={f.id}><h3>Pedido #{f.order_id} · {f.rating}/5</h3><p>{f.comment}</p>{f.handled_at?<p>Tratada</p>:<button disabled={busy} onClick={()=>post({handled_id:f.id})}>Marcar como tratada</button>}</article>)}<h2>Histórico das automações</h2><Pagination page={q.data.messages_pagination?.page} pages={q.data.messages_pagination?.pages} size={size} onPage={n=>setPages({...pages,messages:n})} onSize={n=>{setSize(n);setPages({messages:1,feedback:1});}}/>{q.data.messages.map((m:any)=><article className="card" key={m.id}><strong>{({recovery:'Carrinho',feedback:'Pós-venda',reactivation:'Reativação'} as any)[m.kind]}</strong><p>{m.text||'Aguardando condições de envio'}</p><p>{m.sent_at?'Enviada':m.skipped_at?'Ignorada':m.attempted_at?'Tentativa sem confirmação':'Pendente'} · {m.converted_at?'Compra posterior identificada':''}</p>{m.error&&<p>{m.error}</p>}</article>)}</>}</Feedback></>;
}
