# Generated by Django 5.2.12 on 2026-09-03 02:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "tenants",
            "0011_alter_brandconfig_options_brandconfig_base_font_size_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=160, unique=True)),
                ("payment_id", models.CharField(max_length=80)),
                ("kind", models.CharField(max_length=80)),
                ("environment", models.CharField(max_length=12)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notificação de pagamento",
                "verbose_name_plural": "Notificações de pagamento",
            },
        ),
        migrations.CreateModel(
            name="BillingSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "grace_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[django.core.validators.MaxValueValidator(90)],
                        verbose_name="Dias de tolerância",
                    ),
                ),
                (
                    "pix_enabled",
                    models.BooleanField(default=True, verbose_name="Pix habilitado"),
                ),
                (
                    "boleto_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Boleto habilitado"
                    ),
                ),
                (
                    "card_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Crédito à vista habilitado"
                    ),
                ),
                (
                    "fixed_pix_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.99"),
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Taxa Pix/boleto para cálculo (R$)",
                    ),
                ),
                (
                    "card_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.99"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Taxa crédito (%)",
                    ),
                ),
                (
                    "card_fixed_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.49"),
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Taxa fixa crédito (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de cobrança",
                "verbose_name_plural": "Configuração de cobrança",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Plano")),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(36),
                        ],
                        verbose_name="Meses",
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=199,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                        verbose_name="Valor mensal de referência",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Desconto (%)",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Disponível para compra"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano",
                "ordering": ["months"],
            },
        ),
        migrations.CreateModel(
            name="BillingAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80, verbose_name="Ação")),
                ("detail", models.CharField(max_length=500, verbose_name="Detalhes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="Loja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento da assinatura",
                "verbose_name_plural": "Auditoria de assinaturas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(max_length=80, verbose_name="Plano comprado"),
                ),
                (
                    "months",
                    models.PositiveSmallIntegerField(verbose_name="Meses comprados"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor cobrado"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("BOLETO", "Boleto"),
                            ("CREDIT_CARD", "Crédito à vista"),
                        ],
                        max_length=12,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                (
                    "environment",
                    models.CharField(max_length=12, verbose_name="Ambiente"),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name="ID Asaas",
                    ),
                ),
                ("customer_id_external", models.CharField(blank=True, max_length=80)),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True, max_length=600, verbose_name="Link de pagamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Preparando"),
                            ("UNCERTAIN", "Aguardando conciliação"),
                            ("PENDING", "Aguardando pagamento"),
                            ("OVERDUE", "Cobrança vencida"),
                            ("PAID", "Pagamento confirmado"),
                            ("CANCELLED", "Cancelada"),
                            ("REVIEW", "Estorno / contestação"),
                            ("ERROR", "Falha de emissão"),
                        ],
                        default="NEW",
                        max_length=12,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmada em"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Vencimento da cobrança")),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("issuance_attempted", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="Loja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cobrança",
                "verbose_name_plural": "Cobranças",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "months",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(36),
                        ],
                        verbose_name="Meses",
                    ),
                ),
                (
                    "previous_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimento anterior"
                    ),
                ),
                ("valid_until", models.DateField(verbose_name="Novo vencimento")),
                (
                    "reason",
                    models.CharField(
                        max_length=250, verbose_name="Motivo / comprovante"
                    ),
                ),
                (
                    "manual_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registrado em"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="Loja",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crédito de assinatura",
                "verbose_name_plural": "Créditos de assinatura",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "managed",
                    models.BooleanField(
                        default=False,
                        help_text="Lojas existentes ficam sem cobrança automática até você definir o vencimento e habilitar este controle.",
                        verbose_name="Controlar vencimento desta loja",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Primeiro dia do novo período. A tolerância conta a partir desta data.",
                        null=True,
                        verbose_name="Vencimento",
                    ),
                ),
                (
                    "anchor_day",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                (
                    "grace_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Vazio: usar configuração geral.",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(90)],
                        verbose_name="Tolerância específica (dias)",
                    ),
                ),
                (
                    "manually_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Pagamento não remove esta suspensão.",
                        verbose_name="Suspensão administrativa",
                    ),
                ),
                (
                    "billing_suspended",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="Suspensa por assinatura",
                    ),
                ),
                (
                    "payment_review",
                    models.BooleanField(
                        default=False,
                        help_text="Revise os pagamentos antes de desmarcar.",
                        verbose_name="Bloqueio por estorno/contestação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription",
                        to="tenants.tenant",
                        verbose_name="Loja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura da loja",
                "verbose_name_plural": "Assinaturas das lojas",
            },
        ),
        migrations.CreateModel(
            name="BillingCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("environment", models.CharField(max_length=12)),
                ("provider_id", models.CharField(blank=True, max_length=80)),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Nome / razão social"
                    ),
                ),
                (
                    "document",
                    models.CharField(max_length=14, verbose_name="CPF / CNPJ"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("attempted", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "environment"),
                        name="billing_customer_tenant_env",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="billing_invoice_positive"
            ),
        ),
    ]
