# Generated by Django 5.2.12 on 2026-09-03 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial_plans'),
        ('tenants', '0012_alter_businesshour_tenant_alter_tenant_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingcustomer',
            options={'verbose_name': 'Pagador no Asaas', 'verbose_name_plural': 'Pagadores no Asaas'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['months'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterField(
            model_name='billingaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='attempted',
            field=models.BooleanField(default=False, verbose_name='Cadastro já solicitado ao Asaas'),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Ambiente de testes'), ('production', 'Produção')], max_length=12, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='provider_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID no Asaas'),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant', verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas'),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Recebida em'),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Ambiente de testes'), ('production', 'Produção')], max_length=12, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='event_id',
            field=models.CharField(max_length=160, unique=True, verbose_name='ID da notificação'),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='kind',
            field=models.CharField(max_length=80, verbose_name='Evento do Asaas (código técnico)'),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='payment_id',
            field=models.CharField(max_length=80, verbose_name='ID da cobrança no Asaas'),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processada em'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.invoice', verbose_name='Cobrança'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='manual_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador do registro manual'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_id_external',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID do pagador no Asaas'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Ambiente de testes'), ('production', 'Produção')], max_length=12, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issuance_attempted',
            field=models.BooleanField(default=False, verbose_name='Emissão já solicitada ao Asaas'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última consulta ao Asaas'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='anchor_day',
            field=models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='Dia-base do vencimento'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criada em'),
        ),
    ]
