# Generated by Django 5.2.12 on 2026-09-03 18:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingcustomer_options_alter_plan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Ambiente de testes'), ('production', 'Produção')], max_length=12, unique=True, verbose_name='Ambiente')),
                ('enabled', models.BooleanField(default=False, verbose_name='Emissão automática habilitada')),
                ('start_at', models.DateTimeField(blank=True, help_text='Defina o início da implantação. Não emite notas antigas automaticamente.', null=True, verbose_name='Considerar pagamentos confirmados a partir de')),
                ('service_id', models.CharField(blank=True, max_length=80, verbose_name='ID do serviço municipal no Asaas')),
                ('service_code', models.CharField(blank=True, help_text='Informe o ID acima OU este código, conforme a configuração municipal/nacional da conta Asaas. Não confunda com CNAE.', max_length=40, verbose_name='Código do serviço aceito pelo Asaas')),
                ('service_name', models.CharField(default='Licenciamento da plataforma VemDeDelivery', max_length=200, verbose_name='Nome do serviço')),
                ('description', models.CharField(default='Licenciamento de uso da plataforma VemDeDelivery', max_length=500, verbose_name='Descrição da assinatura')),
            ],
            options={
                'verbose_name': 'Configuração de NFS-e',
                'verbose_name_plural': 'Configurações de NFS-e',
            },
        ),
        migrations.CreateModel(
            name='FiscalCustomerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retain_iss', models.BooleanField(default=False, verbose_name='Reter ISS')),
                ('hold', models.BooleanField(default=True, verbose_name='Pausar emissão para revisão fiscal')),
                ('reason', models.CharField(max_length=400, verbose_name='Orientação contábil / motivo')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.billingcustomer', verbose_name='Pagador (loja e ambiente)')),
            ],
            options={
                'verbose_name': 'Exceção fiscal do pagador',
                'verbose_name_plural': 'Exceções fiscais dos pagadores',
            },
        ),
        migrations.CreateModel(
            name='FiscalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='ID da NFS-e no Asaas')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('UNCERTAIN', 'Solicitação em conciliação'), ('SCHEDULED', 'Agendada'), ('SYNCHRONIZED', 'Enviada à prefeitura'), ('AUTHORIZED', 'Autorizada'), ('ERROR', 'Erro — revisar no Asaas'), ('CANCELED', 'Cancelada'), ('PROCESSING_CANCELLATION', 'Cancelamento em processamento'), ('CANCELLATION_DENIED', 'Cancelamento negado')], default='PENDING', max_length=30, verbose_name='Situação')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Data de emissão / competência')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor integral contratado')),
                ('iss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ISS utilizado (%)')),
                ('payload', models.JSONField(default=dict, verbose_name='Dados fiscais enviados (registro histórico)')),
                ('attempted', models.BooleanField(default=False, verbose_name='Solicitação já enviada')),
                ('review_required', models.BooleanField(default=False, verbose_name='Exige revisão fiscal')),
                ('notice', models.CharField(blank=True, max_length=400, verbose_name='Aviso operacional')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='Número da nota')),
                ('pdf_url', models.URLField(blank=True, max_length=2000, verbose_name='PDF no provedor')),
                ('xml_url', models.URLField(blank=True, max_length=2000, verbose_name='XML no provedor, quando disponível')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Última conciliação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_note', to='billing.invoice', verbose_name='Cobrança')),
            ],
            options={
                'verbose_name': 'Nota fiscal de assinatura',
                'verbose_name_plural': 'Notas fiscais de assinaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Competência (primeiro dia do mês)')),
                ('iss', models.DecimalField(decimal_places=2, help_text='ATENÇÃO: confira no INÍCIO DE CADA MÊS em Contabilizei → Minhas Rotinas → Ver minhas alíquotas. O ISS varia com o faturamento; não use aqui a alíquota total do Simples. Cadastre também quando o percentual permanecer igual.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Alíquota de ISS (%)')),
                ('checked_at', models.DateTimeField(editable=False, null=True, verbose_name='Última conferência registrada')),
                ('checked_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Conferida por')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.fiscalsettings', verbose_name='Configuração fiscal')),
            ],
            options={
                'verbose_name': 'Alíquota mensal de ISS',
                'verbose_name_plural': 'Alíquotas mensais de ISS',
                'constraints': [models.UniqueConstraint(fields=('configuration', 'month'), name='billing_tax_month_unique')],
            },
        ),
    ]
