# Generated by Django 5.2.12 on 2026-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_fiscalsettings_fiscalcustomerrule_fiscalinvoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Competência (primeiro dia do mês)')),
                ('environment', models.CharField(choices=[('sandbox', 'Ambiente de testes'), ('production', 'Produção')], max_length=12, verbose_name='Ambiente')),
                ('filename', models.CharField(editable=False, max_length=200, verbose_name='Nome do arquivo original')),
                ('content', models.BinaryField(verbose_name='CSV original da prefeitura')),
                ('sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Arquivado em')),
            ],
            options={
                'verbose_name': 'CSV municipal para Contabilizei',
                'verbose_name_plural': 'CSVs municipais para Contabilizei',
            },
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='delivery_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Aceito pelo servidor em'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='delivery_checked_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Última tentativa de arquivamento/envio'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='delivery_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, verbose_name='Destinatário da nota'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='delivery_notice',
            field=models.CharField(blank=True, editable=False, max_length=400, verbose_name='Aviso de documentos/e-mail'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SENDING', 'Em envio / verificar se interrompido'), ('SENT', 'Aceito pelo servidor de e-mail'), ('UNCERTAIN', 'Resultado incerto — revisão manual')], default='PENDING', max_length=12, verbose_name='Envio por e-mail'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='pdf_content',
            field=models.BinaryField(null=True, verbose_name='PDF arquivado'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='pdf_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 do PDF'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='xml_content',
            field=models.BinaryField(null=True, verbose_name='XML arquivado'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='xml_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 do XML'),
        ),
    ]
