# Generated by Django 5.2.12 on 2026-09-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_asaasfeesnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalsettings",
            name="nbs_code",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Use o formato oficial aceito pelo Asaas, por exemplo 1.1103.22.00. "
                    "Se informar somente os 9 dígitos, o VemDeDelivery aplica a máscara automaticamente."
                ),
                max_length=32,
                verbose_name="Código NBS",
            ),
        ),
    ]
