# Generated by Django 5.2.12 on 2026-09-03 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppIntegrationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Identificação técnica",
                    ),
                ),
                (
                    "environment",
                    models.CharField(max_length=32, verbose_name="Ambiente"),
                ),
                (
                    "instance",
                    models.CharField(max_length=100, verbose_name="Instância"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Ainda não verificado"),
                            ("open", "Conectado"),
                            ("close", "Desconectado"),
                            ("connecting", "Reconectando"),
                            ("error", "Erro de comunicação/configuração"),
                            ("pairing", "Necessita novo pareamento"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        null=True, verbose_name="Última verificação concluída"
                    ),
                ),
                (
                    "observed_online_at",
                    models.DateTimeField(
                        null=True, verbose_name="Última conexão observada"
                    ),
                ),
                (
                    "online_since",
                    models.DateTimeField(
                        null=True, verbose_name="Conectado continuamente desde"
                    ),
                ),
                (
                    "webhook_at",
                    models.DateTimeField(
                        null=True, verbose_name="Último webhook recebido"
                    ),
                ),
                (
                    "pairing_hint_at",
                    models.DateTimeField(
                        null=True, verbose_name="Indício recente de pareamento"
                    ),
                ),
                ("webhook_pending", models.BooleanField(default=False, editable=False)),
                (
                    "incident",
                    models.UUIDField(
                        editable=False, null=True, verbose_name="Incidente"
                    ),
                ),
                (
                    "down_since",
                    models.DateTimeField(null=True, verbose_name="Indisponível desde"),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tentativas no incidente"
                    ),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(null=True, verbose_name="Próxima tentativa"),
                ),
                (
                    "manual_required",
                    models.BooleanField(
                        default=False, verbose_name="Intervenção manual necessária"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Diagnóstico"
                    ),
                ),
                ("lease_token", models.UUIDField(editable=False, null=True)),
                ("lease_until", models.DateTimeField(editable=False, null=True)),
                (
                    "manual_requested",
                    models.BooleanField(default=False, editable=False),
                ),
                ("action_at", models.DateTimeField(editable=False, null=True)),
                (
                    "manual_actor",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conexão WhatsApp / Evolution",
                "verbose_name_plural": "Conexões WhatsApp / Evolution",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppIntegrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data"),
                ),
                ("kind", models.CharField(max_length=40, verbose_name="Evento")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("incident", models.UUIDField(null=True, verbose_name="Incidente")),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Superadministrador",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="integrations.whatsappintegrationstate",
                        verbose_name="Conexão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento da integração WhatsApp",
                "verbose_name_plural": "Histórico da integração WhatsApp",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="WhatsAppAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="Incidente"
                    ),
                ),
                (
                    "recovery",
                    models.BooleanField(
                        default=False, verbose_name="Aviso de recuperação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sending", "Em envio / resultado ainda não confirmado"),
                            ("sent", "Aceito pelo servidor de e-mail"),
                            ("uncertain", "Resultado incerto — verificar e-mail"),
                            ("skipped", "Cancelado por recuperação"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Envio",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(null=True, verbose_name="Tentativa em"),
                ),
                ("sent_at", models.DateTimeField(null=True, verbose_name="Aceito em")),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrations.whatsappintegrationstate",
                        verbose_name="Conexão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta WhatsApp",
                "verbose_name_plural": "Alertas WhatsApp por e-mail",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("state", "incident", "recovery"),
                        name="unique_whatsapp_incident_alert",
                    )
                ],
            },
        ),
    ]
