# Generated by Django 5.2.12 on 2026-09-28 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_tenant_whatsapp_group_notice'),
        ('orders', '0012_order_payment_flow'),
        ('stores', '0012_category_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('step', models.CharField(default='product', max_length=32)),
                ('data', models.JSONField(default=dict)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='editing', max_length=24)),
                ('environment', models.CharField(blank=True, max_length=12)),
                ('account_id', models.CharField(blank=True, max_length=80)),
                ('provider_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.cart')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='integrations.tenantwhatsappconversation')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppCartReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.product')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='integrations.whatsappcheckout')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('checkout', 'product'), name='wa_unique_reserved_product')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCheckoutReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=160)),
                ('reply', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.tenantwhatsappconversation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'message_id'), name='wa_unique_checkout_message')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOrderNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='integrations.whatsappcheckout')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('checkout', 'recipient'), name='wa_unique_order_recipient')],
            },
        ),
    ]
