# Generated by Django 5.2.12 on 2026-10-08 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_whatsappcheckout_whatsappcartreservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='integrations.tenantwhatsappconversation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'key'), name='conversation_entry_once')],
            },
        ),
    ]
