# Generated by Django 5.2.12 on 2026-08-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "tenants",
            "0011_alter_brandconfig_options_brandconfig_base_font_size_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji opcional, ex.: 🍕",
                        max_length=10,
                        verbose_name="Ícone",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Categoria do marketplace",
                "verbose_name_plural": "Categorias do marketplace",
                "ordering": ("order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="marketplace_is_acti_20975e_idx",
                    ),
                    models.Index(fields=["slug"], name="marketplace_slug_9ad05f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_listed",
                    models.BooleanField(
                        default=True,
                        help_text="Quando desmarcado, a loja continua funcionando no subdomínio, mas não aparece na vitrine geral.",
                        verbose_name="Exibir no marketplace",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Use para priorizar uma loja na vitrine.",
                        verbose_name="Loja em destaque",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quanto maior, mais acima a loja aparece entre lojas equivalentes.",
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Texto compacto exibido no card da loja.",
                        max_length=180,
                        verbose_name="Descrição curta",
                    ),
                ),
                (
                    "search_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Termos adicionais separados por vírgula. Ex.: artesanal, rodízio, lanche, japonesa.",
                        max_length=500,
                        verbose_name="Palavras-chave",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Cidade"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, max_length=2, verbose_name="UF"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Bairro"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "service_radius_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Opcional. Preparado para busca por proximidade no futuro.",
                        max_digits=6,
                        null=True,
                        verbose_name="Raio de atendimento (km)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stores",
                        to="marketplace.marketplacecategory",
                        verbose_name="Categorias",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_profile",
                        to="tenants.tenant",
                        verbose_name="Loja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil no marketplace",
                "verbose_name_plural": "Perfis no marketplace",
                "ordering": ("-is_featured", "-priority", "tenant__name"),
                "indexes": [
                    models.Index(
                        fields=["is_listed", "is_featured"],
                        name="marketplace_is_list_bfffeb_idx",
                    ),
                    models.Index(
                        fields=["city", "state"], name="marketplace_city_04f810_idx"
                    ),
                    models.Index(
                        fields=["neighborhood"], name="marketplace_neighbo_fd7750_idx"
                    ),
                ],
            },
        ),
    ]
