# Generated by Django 5.2.12 on 2026-08-28 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_phone_verified_customer_phone_verified_at"),
        ("marketplace", "0001_initial"),
        (
            "tenants",
            "0011_alter_brandconfig_options_brandconfig_base_font_size_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceFavoriteStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_marketplace_stores",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_favorites",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loja favorita",
                "verbose_name_plural": "Lojas favoritas",
                "indexes": [
                    models.Index(
                        fields=["customer", "created_at"],
                        name="marketplace_custome_032008_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "tenant"),
                        name="unique_marketplace_favorite_store",
                    )
                ],
            },
        ),
    ]
