# Generated by Django 5.2.12 on 2026-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplacefavoritestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Identificador na URL'),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
