# Generated by Django 5.2.12 on 2026-05-13 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_phone_number", models.CharField(max_length=20)),
                ("phone_number_id", models.CharField(max_length=64, unique=True)),
                ("business_account_id", models.CharField(max_length=64)),
                ("access_token", models.CharField(max_length=512)),
                (
                    "verify_token",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Token usado para validar o webhook da Meta.",
                        max_length=128,
                    ),
                ),
                (
                    "app_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Opcional. Usado para validar assinatura HMAC do webhook.",
                        max_length=256,
                    ),
                ),
                (
                    "webhook_subscribed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o webhook já foi registrado na Meta.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_configs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Config",
                "verbose_name_plural": "WhatsApp Configs",
                "ordering": ["-created_at"],
            },
        ),
    ]
