# Generated by Django 5.2.12 on 2026-05-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_remove_tenant_whatsapp_api_key_and_more"),
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_phone", models.CharField(max_length=20)),
                ("user_message", models.TextField()),
                ("ai_response", models.TextField()),
                ("detected_intent", models.CharField(blank=True, max_length=50)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("human_correction", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_global", models.BooleanField(default=False)),
                ("question", models.TextField()),
                ("ideal_response", models.TextField()),
                ("intent_label", models.CharField(max_length=50)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
