# Generated by Django 5.2.12 on 2026-05-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0002_aiconsultation_trainingexample"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingexample",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="AIConsultation",
        ),
        migrations.DeleteModel(
            name="TrainingExample",
        ),
    ]
