# Generated by Django 5.2.12 on 2026-05-11 20:01

import apps.tenants.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "whatsapp_instance_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "whatsapp_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Formato: 5511999999999",
                        max_length=13,
                        unique=True,
                        validators=[apps.tenants.utils.validate_whatsapp_number],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sale_mode",
                    models.CharField(
                        choices=[
                            ("online", "Venda Online (com pagamento)"),
                            ("whatsapp", "Apenas WhatsApp (sem pagamento online)"),
                        ],
                        default="whatsapp",
                        help_text="Define se a loja aceita pagamentos online ou apenas pedidos pelo WhatsApp.",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrandConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#e74c3c",
                        help_text="Cor principal (botões, links)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#2c3e50",
                        help_text="Cor secundária (headers, ícones)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#f39c12",
                        help_text="Cor de destaque (badges, promoções)",
                        max_length=7,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Cor de fundo do site",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#111827", help_text="Cor base do texto", max_length=7
                    ),
                ),
                (
                    "dark_mode_primary",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Cor primária no modo escuro",
                        max_length=7,
                    ),
                ),
                (
                    "dark_mode_background",
                    models.CharField(
                        default="#0f172a",
                        help_text="Fundo no modo escuro",
                        max_length=7,
                    ),
                ),
                (
                    "dark_mode_text",
                    models.CharField(
                        default="#f1f5f9",
                        help_text="Texto no modo escuro",
                        max_length=7,
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="favicons/"),
                ),
                (
                    "banner",
                    models.ImageField(blank=True, null=True, upload_to="banners/"),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_config",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
