# Generated by Django 5.2.12 on 2026-05-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('whatsapp_instance_key', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#e74c3c', max_length=7)),
                ('secondary_color', models.CharField(default='#2c3e50', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_config', to='tenants.tenant')),
            ],
        ),
    ]
