# Generated by Django 5.2.12 on 2026-05-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandconfig",
            name="accent_color",
            field=models.CharField(
                default="#f39c12",
                help_text="Cor de destaque (badges, promoções)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="background_color",
            field=models.CharField(
                default="#ffffff", help_text="Cor de fundo do site", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="dark_mode_background",
            field=models.CharField(
                default="#0f172a", help_text="Fundo no modo escuro", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="dark_mode_primary",
            field=models.CharField(
                default="#3b82f6", help_text="Cor primária no modo escuro", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="dark_mode_text",
            field=models.CharField(
                default="#f1f5f9", help_text="Texto no modo escuro", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="favicons/"),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="text_color",
            field=models.CharField(
                default="#111827", help_text="Cor base do texto", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="primary_color",
            field=models.CharField(
                default="#e74c3c",
                help_text="Cor principal (botões, links)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="secondary_color",
            field=models.CharField(
                default="#2c3e50",
                help_text="Cor secundária (headers, ícones)",
                max_length=7,
            ),
        ),
    ]
