# Generated by Django 5.2.12 on 2026-05-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="whatsapp_api_key",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="whatsapp_instance_key",
        ),
    ]
