# Generated by Django 5.2.12 on 2026-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_brandconfig_accent_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="sale_mode",
            field=models.CharField(
                choices=[
                    ("online", "Venda Online (com pagamento)"),
                    ("whatsapp", "Apenas WhatsApp (sem pagamento online)"),
                ],
                default="whatsapp",
                help_text="Define se a loja aceita pagamentos online ou apenas pedidos pelo WhatsApp.",
                max_length=20,
            ),
        ),
    ]
