# Generated by Django 5.2.12 on 2026-05-20 14:59

import apps.tenants.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_remove_tenant_whatsapp_api_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandconfig",
            options={
                "ordering": ["tenant__name"],
                "verbose_name": "Configuração de Marca",
                "verbose_name_plural": "Configurações de Marca",
            },
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["name"],
                "verbose_name": "Loja",
                "verbose_name_plural": "Lojas",
            },
        ),
        migrations.RemoveField(
            model_name="brandconfig",
            name="custom_domain",
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="accent_color",
            field=models.CharField(
                default="#f39c12",
                max_length=7,
                verbose_name="Cor de destaque (badges, promoções)",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="background_color",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="Cor de fundo do site"
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="banners/",
                verbose_name="Banner da loja",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="dark_mode_background",
            field=models.CharField(
                default="#0f172a", max_length=7, verbose_name="Fundo no modo escuro"
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="dark_mode_primary",
            field=models.CharField(
                default="#3b82f6",
                max_length=7,
                verbose_name="Cor primária no modo escuro",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="dark_mode_text",
            field=models.CharField(
                default="#f1f5f9", max_length=7, verbose_name="Texto no modo escuro"
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicons/",
                verbose_name="Favicon da loja",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logos/",
                verbose_name="Logo da loja (recomendada: 200x200px)",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="primary_color",
            field=models.CharField(
                default="#e74c3c",
                max_length=7,
                verbose_name="Cor principal (botões, links)",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="secondary_color",
            field=models.CharField(
                default="#2c3e50",
                max_length=7,
                verbose_name="Cor secundária (headers, ícones)",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="text_color",
            field=models.CharField(
                default="#111827", max_length=7, verbose_name="Cor base do texto"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="sale_mode",
            field=models.CharField(
                choices=[
                    ("online", "Venda Online (com pagamento)"),
                    ("whatsapp", "Apenas WhatsApp (sem pagamento online)"),
                ],
                default="whatsapp",
                max_length=20,
                verbose_name="Define se a loja aceita pagamentos online ou apenas pedidos pelo WhatsApp.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="whatsapp_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[apps.tenants.utils.validate_whatsapp_number],
                verbose_name="Formato: 5511999999999",
            ),
        ),
    ]
