# Generated by Django 5.2.12 on 2026-05-05 19:29

import apps.tenants.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_sale_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_number",
            field=models.CharField(
                default=5511999999999,
                help_text="Formato: 5511999999999",
                max_length=13,
                unique=True,
                validators=[apps.tenants.utils.validate_whatsapp_number],
            ),
            preserve_default=False,
        ),
    ]
