# Generated by Django 5.2.12 on 2026-07-31 19:33

import apps.tenants.utils
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_brandconfig_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço exibido no cardápio (opcional).', max_length=255, verbose_name='Endereço da loja'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_hours',
            field=models.CharField(blank=True, help_text='Ex: Seg a Sáb, 18h às 23h.', max_length=255, verbose_name='Horário de funcionamento'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor cobrado pela entrega. Deixe 0 para entrega grátis.', max_digits=10, verbose_name='Taxa de entrega'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='delivery_time_estimate',
            field=models.CharField(blank=True, help_text='Ex: 30-45 min.', max_length=60, verbose_name='Tempo estimado de entrega'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Loja ativa'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da loja'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='sale_mode',
            field=models.CharField(choices=[('online', 'Venda Online (com pagamento)'), ('whatsapp', 'Apenas WhatsApp (sem pagamento online)')], default='whatsapp', help_text='Define se a loja aceita pagamentos online ou apenas pedidos pelo WhatsApp.', max_length=20, verbose_name='Modo de venda'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Identificador (subdomínio)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='whatsapp_number',
            field=models.CharField(max_length=13, unique=True, validators=[apps.tenants.utils.validate_whatsapp_number], verbose_name='WhatsApp (formato: 5511999999999)'),
        ),
    ]
