# Generated by Django 5.2.12 on 2026-08-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_address_tenant_business_hours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "neighborhood",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Taxa de entrega (R$)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_zones",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zona de Entrega",
                "verbose_name_plural": "Zonas de Entrega",
                "ordering": ["city", "neighborhood"],
                "unique_together": {("tenant", "city", "neighborhood")},
            },
        ),
    ]
