# Generated by Django 5.2.12 on 2026-08-18 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_deliveryzone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="address",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="business_hours",
        ),
        migrations.AddField(
            model_name="tenant",
            name="pickup_address",
            field=models.CharField(
                blank=True,
                help_text="Endereço exibido ao cliente quando ele escolher retirar o pedido.",
                max_length=255,
                verbose_name="Endereço para retirada",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pickup_city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pickup_complement",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pickup_neighborhood",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pickup_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pickup_zip_code",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.CreateModel(
            name="BusinessHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Dia da semana",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Fechado"),
                ),
                (
                    "opening_time",
                    models.TimeField(blank=True, null=True, verbose_name="Abertura"),
                ),
                (
                    "closing_time",
                    models.TimeField(blank=True, null=True, verbose_name="Fechamento"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_hours",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário de funcionamento",
                "verbose_name_plural": "Horários de funcionamento",
                "ordering": ["weekday", "opening_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "weekday"),
                        name="unique_business_hour_per_tenant_weekday",
                    )
                ],
            },
        ),
    ]
