# Generated by Django 5.2.12 on 2026-08-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_remove_tenant_address_remove_tenant_business_hours_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deliveryzone",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.UniqueConstraint(
                fields=("tenant", "city", "neighborhood"),
                name="unique_delivery_zone_per_tenant",
            ),
        ),
    ]
