# Generated by Django 5.2.12 on 2026-08-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_alter_deliveryzone_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="delivery_fee",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="delivery_time_estimate",
        ),
    ]
