# Generated by Django 5.2.12 on 2026-08-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_remove_tenant_delivery_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="fulfillment_mode",
            field=models.CharField(
                choices=[
                    ("delivery_and_pickup", "Entrega e Retirada"),
                    ("pickup_only", "Apenas Retirada"),
                    ("delivery_only", "Apenas entrega"),
                ],
                default="delivery_and_pickup",
                help_text="Define se a loja oferece entrega e retirada, ou apenas retirada no local.",
                max_length=20,
                verbose_name="Modo de atendimento",
            ),
        ),
    ]
