# Generated by Django 5.2.12 on 2026-08-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_tenant_fulfillment_mode"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="businesshour",
            name="unique_business_hour_per_tenant_weekday",
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="is_closed",
            field=models.BooleanField(default=True, verbose_name="Fechado"),
        ),
    ]
