# Generated by Django 5.2.12 on 2026-08-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0010_remove_businesshour_unique_business_hour_per_tenant_weekday_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandconfig",
            options={
                "ordering": ["tenant__name"],
                "verbose_name": "Configuração de marca",
                "verbose_name_plural": "Configurações de marca",
            },
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="base_font_size",
            field=models.PositiveSmallIntegerField(
                default=16,
                help_text="Valor em pixels.",
                verbose_name="Tamanho base da fonte",
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="border_color",
            field=models.CharField(
                default="#E5E7EB", max_length=7, verbose_name="Cor das bordas"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="border_radius",
            field=models.PositiveSmallIntegerField(
                default=18,
                help_text="Valor em pixels.",
                verbose_name="Arredondamento dos cartões",
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="button_radius",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Valor em pixels.",
                verbose_name="Arredondamento dos botões",
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="button_text_color",
            field=models.CharField(
                default="#FFFFFF", max_length=7, verbose_name="Cor do texto dos botões"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="card_background_color",
            field=models.CharField(
                default="#FFFFFF", max_length=7, verbose_name="Cor de fundo dos cartões"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="card_shadow",
            field=models.BooleanField(
                default=True, verbose_name="Exibir sombra nos cartões"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="compact_product_cards",
            field=models.BooleanField(
                default=False, verbose_name="Usar cartões de produto compactos"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="danger_color",
            field=models.CharField(
                default="#DC2626", max_length=7, verbose_name="Cor de erro"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="dark_mode_border_color",
            field=models.CharField(
                default="#374151",
                max_length=7,
                verbose_name="Cor das bordas no modo escuro",
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="dark_mode_card_background",
            field=models.CharField(
                default="#1F2937",
                max_length=7,
                verbose_name="Cor dos cartões no modo escuro",
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="dark_mode_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Permitir modo escuro"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="dark_mode_muted_text",
            field=models.CharField(
                default="#9CA3AF",
                max_length=7,
                verbose_name="Cor do texto secundário no modo escuro",
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("Inter", "Inter"),
                    ("Poppins", "Poppins"),
                    ("Roboto", "Roboto"),
                    ("Montserrat", "Montserrat"),
                    ("Nunito", "Nunito"),
                ],
                default="Inter",
                max_length=50,
                verbose_name="Fonte principal",
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="header_style",
            field=models.CharField(
                choices=[
                    ("solid", "Cor sólida"),
                    ("gradient", "Gradiente"),
                    ("transparent", "Transparente"),
                ],
                default="solid",
                max_length=20,
                verbose_name="Estilo do cabeçalho",
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="hover_effect",
            field=models.BooleanField(
                default=True, verbose_name="Exibir efeito ao passar o mouse"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="muted_text_color",
            field=models.CharField(
                default="#6B7280", max_length=7, verbose_name="Cor do texto secundário"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="show_category_icons",
            field=models.BooleanField(
                default=True, verbose_name="Exibir ícones nas categorias"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="show_product_description",
            field=models.BooleanField(
                default=True, verbose_name="Exibir descrição dos produtos"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="show_product_image",
            field=models.BooleanField(
                default=True, verbose_name="Exibir imagem dos produtos"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="show_search_bar",
            field=models.BooleanField(
                default=True, verbose_name="Exibir barra de busca"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="success_color",
            field=models.CharField(
                default="#16A34A", max_length=7, verbose_name="Cor de sucesso"
            ),
        ),
        migrations.AddField(
            model_name="brandconfig",
            name="warning_color",
            field=models.CharField(
                default="#F59E0B", max_length=7, verbose_name="Cor de aviso"
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="accent_color",
            field=models.CharField(
                default="#FBBF24",
                help_text="Usada em promoções, selos e elementos de destaque.",
                max_length=7,
                verbose_name="Cor de destaque",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="background_color",
            field=models.CharField(
                default="#FFF7ED", max_length=7, verbose_name="Cor de fundo do site"
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Recomendado: imagem horizontal de alta qualidade.",
                null=True,
                upload_to="banners/",
                verbose_name="Banner da loja",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="dark_mode_background",
            field=models.CharField(
                default="#111827",
                max_length=7,
                verbose_name="Cor de fundo no modo escuro",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="dark_mode_primary",
            field=models.CharField(
                default="#FB923C",
                max_length=7,
                verbose_name="Cor principal no modo escuro",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="dark_mode_text",
            field=models.CharField(
                default="#F9FAFB",
                max_length=7,
                verbose_name="Cor do texto no modo escuro",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Recomendado: 200x200 px.",
                null=True,
                upload_to="logos/",
                verbose_name="Logo da loja",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="primary_color",
            field=models.CharField(
                default="#FF5A1F",
                help_text="Usada em botões, links e ações principais.",
                max_length=7,
                verbose_name="Cor principal",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="secondary_color",
            field=models.CharField(
                default="#1F2937",
                help_text="Usada em cabeçalhos, ícones e elementos de apoio.",
                max_length=7,
                verbose_name="Cor secundária",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_config",
                to="tenants.tenant",
                verbose_name="Loja",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="text_color",
            field=models.CharField(
                default="#111827", max_length=7, verbose_name="Cor principal do texto"
            ),
        ),
    ]
