# Generated by Django 5.2.12 on 2026-09-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_brandconfig_options_brandconfig_base_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='tenants.tenant', verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criada em'),
        ),
    ]
