# Generated by Django 5.2.12 on 2026-08-27 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0003_customer_phone_verified_customer_phone_verified_at"),
        ("orders", "0005_order_customer_name"),
        (
            "tenants",
            "0011_alter_brandconfig_options_brandconfig_base_font_size_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nome da campanha"),
                ),
                (
                    "code",
                    models.CharField(max_length=40, verbose_name="Código do cupom"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentual"),
                            ("fixed_amount", "Valor fixo"),
                            ("free_delivery", "Frete grátis"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de desconto",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor do desconto",
                    ),
                ),
                (
                    "minimum_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor mínimo do pedido",
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("all", "Todos os clientes"),
                            ("first_order", "Primeira compra"),
                            ("inactive", "Clientes inativos"),
                            ("specific", "Clientes específicos"),
                            ("frequent", "Clientes frequentes"),
                            ("never_ordered", "Nunca compraram nesta loja"),
                        ],
                        default="all",
                        max_length=30,
                        verbose_name="Público da campanha",
                    ),
                ),
                (
                    "inactive_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dias sem comprar"
                    ),
                ),
                (
                    "minimum_orders",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Quantidade mínima de pedidos",
                    ),
                ),
                (
                    "minimum_spent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor mínimo já gasto",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Início da campanha")),
                ("ends_at", models.DateTimeField(verbose_name="Fim da campanha")),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Limite total de utilizações",
                    ),
                ),
                (
                    "usage_limit_per_customer",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Limite de uso por cliente"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_campaigns",
                        to="tenants.tenant",
                        verbose_name="Loja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campanha de cupom",
                "verbose_name_plural": "Campanhas de cupons",
            },
        ),
        migrations.CreateModel(
            name="CouponAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Atribuído em"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_assignments",
                        to="customers.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="coupons.couponcampaign",
                        verbose_name="Campanha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente da campanha",
                "verbose_name_plural": "Clientes da campanha",
            },
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor do desconto",
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Utilizado em"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="coupons.couponcampaign",
                        verbose_name="Campanha",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_redemptions",
                        to="customers.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_redemption",
                        to="orders.order",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso de cupom",
                "verbose_name_plural": "Usos de cupons",
            },
        ),
        migrations.AddConstraint(
            model_name="couponcampaign",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_coupon_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="couponassignment",
            constraint=models.UniqueConstraint(
                fields=("campaign", "customer"), name="unique_customer_per_campaign"
            ),
        ),
    ]
