# Generated by Django 5.2.12 on 2026-08-27 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponcampaign",
            name="ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Deixe em branco para uma campanha sem data de encerramento.",
                null=True,
                verbose_name="Fim da campanha",
            ),
        ),
        migrations.AlterField(
            model_name="couponcampaign",
            name="starts_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Início da campanha"
            ),
        ),
    ]
