# Generated by Django 5.2.12 on 2026-08-27 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_alter_couponcampaign_ends_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponcampaign",
            name="starts_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Se deixar em branco, a campanha começa imediatamente.",
                verbose_name="Início da campanha",
            ),
        ),
    ]
