# Generated by Django 5.2.12 on 2026-05-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        ("tenants", "0002_remove_tenant_whatsapp_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("product", "Produto"),
                            ("category", "Categoria"),
                            ("store_info", "Info da Loja"),
                            ("manual", "Manual / FAQ"),
                            ("global_pattern", "Padrão Global"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("content", models.TextField()),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("is_global", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_hours",
                    models.TextField(
                        help_text="Ex: Seg a Sex das 18h às 23h. Sáb e Dom das 18h às 00h."
                    ),
                ),
                (
                    "delivery_fee_policy",
                    models.TextField(
                        help_text="Ex: Taxa fixa de R$ 5,00 para todo o bairro. Grátis acima de R$ 50,00."
                    ),
                ),
                (
                    "payment_methods",
                    models.TextField(
                        help_text="Ex: Aceitamos Pix, Cartão de Crédito e Débito na entrega."
                    ),
                ),
                (
                    "general_faq",
                    models.TextField(
                        blank=True,
                        help_text="Informações gerais extras que a IA deve saber.",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de IA da Loja",
            },
        ),
    ]
