# Generated by Django 5.2.12 on 2026-05-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_knowledgechunk_storeintelligence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeintelligence",
            name="tenant",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="halfproduct",
            options={
                "verbose_name": "Sabor para meio a meio",
                "verbose_name_plural": "Sabores para meio a meio",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-is_featured", "name"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["order"],
                "verbose_name": "Imagem de produto",
                "verbose_name_plural": "Imagens de produto",
            },
        ),
        migrations.DeleteModel(
            name="KnowledgeChunk",
        ),
        migrations.DeleteModel(
            name="StoreIntelligence",
        ),
    ]
