# Generated by Django 5.2.12 on 2026-05-06 17:18

import apps.stores.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_alter_product_category"),
        ("tenants", "0004_tenant_whatsapp_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="HalfProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sabor para Meio a Meio",
                "verbose_name_plural": "Sabores para Meio a Meio",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/images/%Y/%m/%d/",
                        validators=[apps.stores.models.validate_image_resolution],
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Imagem de produto",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-is_featured", "name"]},
        ),
        migrations.RemoveField(
            model_name="category",
            name="tenant",
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="allergens",
            field=models.CharField(
                blank=True, help_text="Ex: glúten, leite, ovo", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="calories",
            field=models.PositiveIntegerField(
                blank=True, help_text="Calorias por porção", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_spicy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="max_order_qty",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="min_order_qty",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="prep_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Tempo de preparo em minutos", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="primary_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m/%d/",
                validators=[apps.stores.models.validate_image_resolution],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(
                blank=True, help_text="Quantidade em estoque (se aplicável)", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso em gramas",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="stores_prod_slug_d4cb14_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="stores_prod_name_f67284_idx"),
        ),
        migrations.AddField(
            model_name="halfproduct",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="half_variant",
                to="stores.product",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="stores.product",
            ),
        ),
    ]
