# Generated by Django 5.2.12 on 2026-05-25 15:12

import apps.stores.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_remove_storeintelligence_tenant_and_more"),
        ("tenants", "0003_alter_brandconfig_options_alter_tenant_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomizationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Escolha sua Borda, Adicionais", max_length=100
                    ),
                ),
                (
                    "apply_to",
                    models.CharField(
                        choices=[
                            ("whole", "Inteira"),
                            ("half", "Meia"),
                            ("both", "Ambas"),
                        ],
                        default="whole",
                        help_text="Onde esse grupo aparecerá na modal",
                        max_length=10,
                    ),
                ),
                (
                    "min_options",
                    models.PositiveIntegerField(
                        default=0, help_text="Mínimo de opções (0 para opcional)"
                    ),
                ),
                (
                    "max_options",
                    models.PositiveIntegerField(
                        default=1, help_text="Máximo de opções permitidas"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customization_groups",
                        to="stores.category",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Personalização",
                "verbose_name_plural": "Grupos de Personalização",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomizationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="customizations/%Y/%m/%d/",
                        validators=[apps.stores.models.validate_image_resolution],
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="stores.customizationgroup",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opção de Personalização",
                "verbose_name_plural": "Opções de Personalização",
                "ordering": ["order", "name"],
            },
        ),
    ]
