# Generated by Django 5.2.12 on 2026-06-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_customizationgroup_customizationoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Dias da semana em que o produto aparece no cardápio. Deixe vazio para aparecer todos os dias.",
            ),
        ),
    ]
