# Generated by Django 5.2.12 on 2026-08-18 17:39

import apps.stores.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_product_available_days"),
        ("tenants", "0004_tenant_address_tenant_business_hours_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customizationgroup",
            options={
                "ordering": ["order", "label__name"],
                "verbose_name": "Grupo de Personalização",
                "verbose_name_plural": "Grupos de Personalização",
            },
        ),
        migrations.RemoveField(
            model_name="customizationgroup",
            name="name",
        ),
        migrations.AlterField(
            model_name="customizationgroup",
            name="apply_to",
            field=models.CharField(
                choices=[("whole", "Inteira"), ("half", "Meia"), ("both", "Ambas")],
                default="whole",
                help_text="Onde esse grupo aparecerá na modal",
                max_length=10,
                verbose_name="Aplicar a",
            ),
        ),
        migrations.AlterField(
            model_name="customizationgroup",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customization_groups",
                to="stores.category",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="customizationgroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="customizationgroup",
            name="max_options",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Máximo de opções permitidas",
                verbose_name="Máximo de opções",
            ),
        ),
        migrations.AlterField(
            model_name="customizationgroup",
            name="min_options",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Mínimo de opções (0 para opcional)",
                verbose_name="Mínimo de opções",
            ),
        ),
        migrations.AlterField(
            model_name="customizationgroup",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem"),
        ),
        migrations.AlterField(
            model_name="customizationoption",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="customizationoption",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customizations/%Y/%m/%d/",
                validators=[apps.stores.models.validate_image_resolution],
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="customizationoption",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Disponível"),
        ),
        migrations.AlterField(
            model_name="customizationoption",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="customizationoption",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem"),
        ),
        migrations.AlterField(
            model_name="customizationoption",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Preço",
            ),
        ),
        migrations.CreateModel(
            name="CustomizationGroupLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Adicionais, Bordas, Molhos",
                        max_length=100,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rótulo de Grupo de Personalização",
                "verbose_name_plural": "Rótulos de Grupos de Personalização",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customizationgroup",
            name="label",
            field=models.ForeignKey(
                blank=True,
                help_text="Selecione um rótulo existente ou crie um novo (ex: Adicionais, Bordas)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="stores.customizationgrouplabel",
                verbose_name="Nome do grupo",
            ),
        ),
        migrations.AddConstraint(
            model_name="customizationgrouplabel",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_label_name_per_tenant"
            ),
        ),
    ]
