# Generated by Django 5.2.12 on 2026-08-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_alter_customizationgroup_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customizationgroup",
            options={
                "ordering": ["label__name"],
                "verbose_name": "Grupo de Personalização",
                "verbose_name_plural": "Grupos de Personalização",
            },
        ),
        migrations.AlterModelOptions(
            name="customizationoption",
            options={
                "ordering": ["name"],
                "verbose_name": "Opção de Personalização",
                "verbose_name_plural": "Opções de Personalização",
            },
        ),
        migrations.RemoveField(
            model_name="customizationgroup",
            name="order",
        ),
        migrations.RemoveField(
            model_name="customizationoption",
            name="order",
        ),
    ]
