# Generated by Django 5.2.12 on 2026-08-18 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0007_alter_customizationgroup_options_and_more"),
        ("tenants", "0005_deliveryzone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "neighborhood",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Taxa de entrega"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zona de Entrega",
                "verbose_name_plural": "Zonas de Entrega",
                "ordering": ["city", "neighborhood"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "city", "neighborhood"),
                        name="unique_store_delivery_zone_per_tenant",
                    )
                ],
            },
        ),
    ]
