# Generated by Django 5.2.12 on 2026-08-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0008_deliveryzone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeliveryZone",
        ),
    ]
