# Generated by Django 5.2.12 on 2026-09-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_delete_deliveryzone'),
        ('tenants', '0011_alter_brandconfig_options_brandconfig_base_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vazio: sem controle. Zero: esgotado. Inclui reservas da revisão (30 min). A baixa ocorre ao abrir WhatsApp; cada metade consome 0,5 unidade.', max_digits=12, null=True, verbose_name='Estoque físico'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__isnull', True), ('stock__gte', 0), _connector='OR'), name='product_stock_nonnegative'),
        ),
    ]
