# Generated by Django 5.2.12 on 2026-09-03 15:39

import apps.stores.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Identificador na URL'),
        ),
        migrations.AlterField(
            model_name='customizationoption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='stores.customizationgroup', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='halfproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='halfproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='halfproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='half_variant', to='stores.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, help_text='Ex.: glúten, leite, ovo', max_length=255, verbose_name='Alérgenos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text='Dias da semana em que o produto aparece no cardápio. Deixe vazio para aparecer todos os dias.', verbose_name='Dias disponíveis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Calorias por porção', null=True, verbose_name='Calorias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Produto em destaque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_spicy',
            field=models.BooleanField(default=False, verbose_name='Picante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Vegano'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_order_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade máxima por pedido'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade mínima por pedido'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prep_time',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo de preparo em minutos', null=True, verbose_name='Tempo de preparo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', validators=[apps.stores.models.validate_image_resolution], verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promocional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Código interno (SKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, verbose_name='Identificador na URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso em gramas', max_digits=7, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/%Y/%m/%d/', validators=[apps.stores.models.validate_image_resolution], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.product', verbose_name='Produto'),
        ),
    ]
