import { useEffect, useRef, useState } from "react";
import { CSRF, OrderSummary, PostButton } from "./PublicApp";
export const money = (value: any) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }).replace(/\u00a0/g, " ");
export async function requestJSON(url: string, data: any, body?: any) {
  const response = await fetch(url, {credentials: "same-origin", headers: {Accept: "application/json", ...(body !== undefined ? {"Content-Type": "application/json", "X-CSRFToken": data.csrf} : {})}, ...(body !== undefined ? {method: "POST", body: JSON.stringify(body)} : {})});
  const result = await response.json().catch(() => ({error: "Não foi possível concluir. Atualize a página e tente novamente."}));
  if (!response.ok || result.success === false) throw new Error(result.error || result.message || "Não foi possível concluir.");
  return result;
}
export function Choices({product, bucket, allowed, selections, onChange}: any) {
  const [groups, setGroups] = useState<any[]>([]), [error, setError] = useState("");
  useEffect(() => { let active = true; setGroups([]); setError(""); requestJSON(`/api/product/${product.id}/customizations/`, {}).then(r => { if(active) setGroups(r.groups); }).catch(e => {if(active) setError(e.message);}); return () => {active=false;}; }, [product.id]);
  return <>{error && <p role="alert">{error}</p>}{groups.filter(g => !allowed || allowed.includes(g.apply_to)).map(group => <fieldset key={group.id}><legend>{group.name} · escolha {group.min_options} a {group.max_options || "várias"}</legend>{group.options.map((option:any) => <label className="choice" key={option.id}><input type="checkbox" checked={selections.some((s:any) => s.group_id === group.id && s.option_id === option.id)} onChange={e => onChange(bucket, e.target.checked ? [...selections, {group_id:group.id,option_id:option.id}] : selections.filter((s:any) => s.option_id !== option.id))}/>{option.name} {Number(option.price) > 0 && `+ ${money(option.price)}`}{option.description && <small>{option.description}</small>}</label>)}</fieldset>)}</>;
}
export function ProductDialog({data, product, products, close}: any) {
  const [half, setHalf] = useState(false), [secondId,setSecondId] = useState(String(product.id));
  const [qty,setQty]=useState(product.min_qty), [notes,setNotes]=useState(""), [notes1,setNotes1]=useState(""), [notes2,setNotes2]=useState("");
  const [selections,setSelections]=useState<any>({}), [error,setError]=useState(""), [busy,setBusy]=useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => {dialog.current?.showModal();try{if(localStorage.getItem("vdd_analytics_permission")==="yes")void requestJSON("/eventos/loja/",data,{stage:"product",consent:true}).catch(()=>{});}catch{}}, []);
  const second = products.find((p:any) => String(p.id) === secondId) || product;
  const change = (key:string, list:any[]) => setSelections((old:any) => ({...old,[key]:list}));
  async function add() {setBusy(true);setError("");try {
    await requestJSON(half ? "/checkout/checkout/add-half-half/" : "/checkout/add/", data, {product_id:product.id,quantity:qty,notes,is_half:half,...(half ? {product_ids:[product.id,second.id],customizations_whole:selections.whole||[],customizations_half1:selections.half1||[],customizations_half2:selections.half2||[],notes_half1:notes1,notes_half2:notes2} : {customizations:selections.whole||[]})});
    window.location.assign("/checkout/cart/");
  } catch(e:any){setError(e.message);setBusy(false);}}
  return <dialog ref={dialog} onCancel={close} className="product-dialog"><button onClick={close} aria-label="Fechar produto">Fechar ×</button><h2>{product.name}</h2><div className="product-gallery">{(product.images.length ? product.images : [product.image]).filter(Boolean).map((src:string) => <img key={src} src={src} alt={product.name}/>)}</div><p>{product.description}</p><strong>{money(product.price)}</strong><p>{product.is_vegan && "Vegano · "}{product.is_spicy && "Picante · "}{product.allergens && `Alérgenos: ${product.allergens}`}</p>{product.prep_time && <p>Preparo: {product.prep_time} min</p>}{product.half_enabled && <label className="choice"><input type="checkbox" checked={half} onChange={e=>{setHalf(e.target.checked);setSelections({});}}/>Montar meio a meio</label>}{half && <label className="public-field">Segundo sabor<select value={secondId} onChange={e=>{setSecondId(e.target.value);change("half2",[]);}}>{products.filter((p:any)=>p.half_enabled&&p.category_id===product.category_id&&p.available).map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>}
    <Choices product={product} bucket="whole" allowed={half ? ["whole","both"] : undefined} selections={selections.whole||[]} onChange={change}/>
    {half && <><h3>Primeira metade: {product.name}</h3><Choices product={product} bucket="half1" allowed={["half"]} selections={selections.half1||[]} onChange={change}/><label className="public-field">Observação da primeira metade<textarea value={notes1} onChange={e=>setNotes1(e.target.value)}/></label><h3>Segunda metade: {second.name}</h3><Choices product={second} bucket="half2" allowed={["half"]} selections={selections.half2||[]} onChange={change}/><label className="public-field">Observação da segunda metade<textarea value={notes2} onChange={e=>setNotes2(e.target.value)}/></label></>}
    <label className="public-field">Quantidade<input type="number" min={product.min_qty} max={product.max_qty} value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label className="public-field">Observações<textarea maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><p>Os valores finais e as opções serão conferidos pela loja ao adicionar.</p>{error && <p role="alert">{error}</p>}<button onClick={add} disabled={busy||!product.available}>{busy?"Adicionando…":"Adicionar ao carrinho"}</button></dialog>;
}
export function Catalog({data}:any) {
  const [search,setSearch]=useState(""), [selected,setSelected]=useState<any>(null);
  const brand=data.store?.brand||{};
  const products = data.props.categories.flatMap((c:any)=>c.products);
  useEffect(()=>{const q=new URLSearchParams(window.location.search).get("q");if(q)setSearch(q);const p=products.find((p:any)=>p.slug===data.props.open_product_slug);if(p)setSelected(p);},[]);
  return <div data-open-product-slug={data.props.open_product_slug}>{data.store?.banner && <img className="store-banner" src={data.store.banner} alt=""/>}<p>{data.store?.is_open ? "Aberto agora" : "Fechado agora"}</p><details><summary>Horários e entrega</summary>{data.store?.hours?.map((h:any,n:number)=><p key={n}>{h.day}: {h.closed?"Fechado":`${h.open} — ${h.close}`}</p>)}{data.store?.pickup_address&&<p>Retirada: {data.store.pickup_address}</p>}{data.props.delivery_zones.map((z:any,n:number)=><p key={n}>{z.city} — {z.neighborhood}: {money(z.fee)}</p>)}</details>{data.props.deep_link_unavailable&&<p role="alert">Este produto não está disponível no momento.</p>}{brand.show_search_bar!==false&&<label className="public-field">Buscar no cardápio<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label>}<nav className="category-nav">{data.props.categories.map((c:any)=><a key={c.id} href={`#category-${c.id}`}>{c.name}</a>)}</nav>{data.props.categories.map((category:any)=><section key={category.id} id={`category-${category.id}`}><h2>{category.name}</h2><div className="public-grid">{category.products.filter((p:any)=>`${p.name} ${p.description}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map((p:any)=><article className={`public-card product-card ${p.is_featured?"product-card-featured":""}`} data-product-price={p.price} data-product-slug={p.slug} key={p.id}>{brand.show_product_image!==false && p.image && <img src={p.image} alt={p.name} loading="lazy"/>}<h3><a href={`/produto/${p.slug}/`} onClick={e=>{e.preventDefault();setSelected(p);}}>{p.name}</a></h3>{brand.show_product_description!==false&&<p>{p.description}</p>}{p.is_featured&&<span className="product-featured absolute top-3 right-3">Destaque</span>}<p>{p.is_vegan&&<span>Vegano </span>}{p.is_spicy&&<span>Picante </span>}{p.prep_time&&<span>{`~${p.prep_time} min `}</span>}{p.weight&&<span>{`${Number(p.weight)} g `}</span>}{p.calories&&<span>{`${p.calories} kcal`}</span>}</p>{p.sale_price!==null&&<><span>OFERTA </span><del>{money(p.original_price)}</del></>} <strong>{money(p.price)}</strong><button disabled={!p.available} onClick={()=>setSelected(p)}>{p.available?"Escolher":"Esgotado"}</button></article>)}</div></section>)}{!products.length && <p>Nenhum produto disponível no momento.</p>}<a className="cart-link" href="/checkout/cart/">Ver carrinho ({data.store?.cart_count||0})</a>{selected&&<ProductDialog key={selected.id} product={selected} products={products} data={data} close={()=>setSelected(null)}/>}</div>;
}
function CartItem({item,data,onUpdate}:any){
  const [qty,setQty]=useState(item.quantity),[notes,setNotes]=useState(item.notes),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function mutate(url:string,body:any){setBusy(true);setError("");try{await requestJSON(url,data,body);await onUpdate();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  const combo=item.combination_details;
  return <article className="public-card"><h2>{item.name}</h2><p>{money(item.price)} cada · <strong>{money(item.total)}</strong></p>{Object.entries({customizations:"Adicionais",customizations_whole:"Inteira",customizations_half1:"Primeira metade",customizations_half2:"Segunda metade"}).map(([bucket,label])=><div key={bucket}>{combo[bucket]?.map((option:any,index:number)=><p key={index}>{label}: {option.option_name} (+ {money(option.price)}) {option.can_remove_from_cart && <button disabled={busy} onClick={()=>mutate(`/checkout/carrinho/item/${item.id}/opcional/remover/`,{bucket,index})}>Remover opcional</button>}</p>)}</div>)}{combo.notes_half1&&<p>Primeira metade: {combo.notes_half1}</p>}{combo.notes_half2&&<p>Segunda metade: {combo.notes_half2}</p>}<label className="public-field">Quantidade<input type="number" value={qty} min={item.min_qty} max={item.max_qty} onChange={e=>setQty(Number(e.target.value))}/></label><button disabled={busy} onClick={()=>mutate(`/checkout/update_quantity/${item.id}/`,{quantity:qty})}>Atualizar quantidade</button><label className="public-field">Observações<textarea value={notes} maxLength={1000} onChange={e=>setNotes(e.target.value)}/></label><button disabled={busy} onClick={()=>mutate(`/checkout/update_notes/${item.id}/`,{notes})}>Salvar observações</button><button disabled={busy} onClick={()=>mutate(`/checkout/remove/${item.id}/`,{})}>Remover item</button>{error&&<p role="alert">{error}</p>}</article>;
}
export function Cart({data}:any){const [current,setCurrent]=useState(data);async function refresh(){setCurrent(await requestJSON("/checkout/cart/",data));}const p=current.props;return <><a href="/">Continuar comprando</a>{data.user?.authenticated&&<form method="post" action="/preferencias/mensagens/"><CSRF data={data}/><label className="choice"><input type="checkbox" name="allowed"/>Autorizo lembretes de carrinho, pesquisa de satisfação e novidades desta loja pelo WhatsApp.</label><button>Salvar preferência de mensagens</button></form>}{p.items.map((item:any)=><CartItem key={`${item.id}-${item.price}-${item.quantity}`} item={item} data={data} onUpdate={refresh}/>)}{!p.items.length?<p>Seu carrinho está vazio.</p>:<section className="public-card"><p>Subtotal: {money(p.subtotal)}</p><p>Entrega: {p.delivery_fee_display}</p><strong>Total: {money(p.total)}</strong><p>{p.checkout_mode_hint}</p><a href="/checkout/checkout/">Escolher endereço e finalizar</a></section>}</>;}
export function AddressFields({initial={},prefix="",onChange}:any){
 const [address,setAddress]=useState<any>(initial),[error,setError]=useState("");
 function update(key:string,value:string){const next={...address,[key]:value};setAddress(next);onChange?.(next);}
 async function cep(){const value=String(address.zip_code||"").replace(/\D/g,"");if(value.length!==8)return;try{const result=await requestJSON(`/api/cep/${value}/`,{});const next={...address,...result};setAddress(next);onChange?.(next);setError("");}catch(e:any){setError(e.message);}}
 return <>{[["zip_code","CEP"],["street","Rua"],["number","Número"],["complement","Complemento"],["neighborhood","Bairro"],["city","Cidade"],["state","UF"],["reference","Referência"]].map(([key,label])=><label className="public-field" key={key}>{label}<input name={prefix+(key==="zip_code"?"cep":key==="street"?"address":key)} value={address[key]||""} onChange={e=>update(key,e.target.value)} onBlur={key==="zip_code"?cep:undefined} required={["street","number","neighborhood","city"].includes(key)} maxLength={key==="state"?2:200}/></label>)}{error&&<p role="alert">{error}</p>}</>;
}
export function Checkout({data}:any){
 const p=data.props;const [mode,setMode]=useState(data.store.accepts_delivery?"delivery":"pickup"),[flow,setFlow]=useState("in_person"),[payment,setPayment]=useState("pix"),[saved,setSaved]=useState(p.default_address?String(p.default_address.id):""),[address,setAddress]=useState(p.global_delivery_location||{}),[fee,setFee]=useState<any>(null);
 useEffect(()=>{let active=true;const a=p.customer_addresses.find((a:any)=>String(a.id)===saved)||address;requestJSON(`/api/delivery-fee/?${new URLSearchParams({delivery_type:mode,city:a.city||"",neighborhood:a.neighborhood||""})}`,data).then(r=>{if(active)setFee(r);}).catch(()=>{if(active)setFee(null);});return()=>{active=false;};},[mode,saved,address.city,address.neighborhood]);
 return <form method="post"><CSRF data={data}/><input type="hidden" name="checkout_token" value={p.checkout_token}/><section className="public-card"><h2>Seu pedido</h2>{p.cart_items.map((i:any,n:number)=><p key={n}>{i.quantity}× {i.name} · {money(i.line_total)}{i.notes&&<small> · {i.notes}</small>}</p>)}<p>Subtotal: {money(p.subtotal)}</p><p>{fee?.fee_display||"A taxa será confirmada conforme o endereço."}</p></section><section className="public-card"><h2>Contato</h2><label className="public-field">Nome completo<input name="full_name" defaultValue={p.initial_full_name} required maxLength={150}/></label><label className="public-field">WhatsApp<input type="tel" name="phone" defaultValue={p.initial_phone} required maxLength={20}/></label><h2>Recebimento</h2>{p.scheduling_enabled&&<label className="public-field">Agendar entrega ou retirada (opcional)<input type="datetime-local" name="scheduled_for"/><small>Horário de São Paulo. A loja confere antecedência e disponibilidade.</small></label>}<label className="public-field">Modalidade<select name="delivery_type" value={mode} onChange={e=>setMode(e.target.value)}>{data.store.accepts_delivery&&<option value="delivery">Entrega</option>}{data.store.accepts_pickup&&<option value="pickup">Retirada</option>}</select></label>{mode==="pickup"?<p>{p.store_address}</p>:<>{p.customer_addresses.length>0&&<label className="public-field">Endereço salvo<select name="customer_address_id" value={saved} onChange={e=>setSaved(e.target.value)}><option value="">Informar outro endereço</option>{p.customer_addresses.map((a:any)=><option key={a.id} value={a.id}>{a.label}: {a.street}, {a.number}</option>)}</select></label>}{!saved&&<AddressFields initial={address} onChange={setAddress}/>}</>}</section><section className="public-card"><h2>Pagamento</h2><label className="public-field">Quando pagar<select name="payment_flow" value={flow} onChange={e=>{setFlow(e.target.value);setPayment("pix");}}><option value="in_person">Na entrega / retirada</option>{p.online_payment_available&&<option value="online">Online pelo Asaas</option>}</select></label><label className="public-field">Forma<select name="payment_method" value={payment} onChange={e=>setPayment(e.target.value)}><option value="pix">Pix</option><option value="credit_card">Cartão de crédito</option>{flow==="in_person"&&<><option value="debit_card">Cartão de débito</option><option value="cash">Dinheiro</option></>}</select></label>{payment==="cash"&&<label className="public-field">Troco para<input type="number" name="change_for" min={0} step="0.01"/></label>}<label className="public-field">Cupom<input name="coupon_code" maxLength={50}/></label><p>O desconto, a taxa e o total definitivo aparecem na revisão.</p><button>Revisar pedido</button></section></form>;
}
export function Review({data}:any){const p=data.props,o=p.order,payment=p.payment;const base=`/pedido/${o.public_token}`;return <><OrderSummary order={{...o,repeat_url:null}} data={data}/>{payment&&<p>Situação do pagamento: {payment.label}</p>}{o.payment_flow==="online"&&payment?.status!=="PAID"?<>{payment?.checkout_url?<a href={payment.checkout_url}>Continuar pagamento no Asaas</a>:<PostButton data={data} action={`${base}/pagar/`}>Pagar online com Asaas</PostButton>}<PostButton data={data} action={`${base}/pagamento/atualizar/`}>Já paguei — verificar confirmação</PostButton></>:<>{payment?.confirmation_code&&<p>Código de confirmação: <strong>{payment.confirmation_code}</strong></p>}<PostButton data={data} action={`${base}/whatsapp/`}>Confirmar e enviar pedido pelo WhatsApp</PostButton></>}<PostButton data={data} action={`${base}/editar/`}>Alterar pedido</PostButton><p>A revisão e a reserva de estoque valem por 30 minutos. O backend confere novamente valores e disponibilidade ao confirmar.</p></>;}
