function Terms() {return <>
<section id="plataforma"><h2>1. Plataforma e responsável</h2>
<p>O <strong>VemDeDelivery</strong> é mantido pela <strong>COBRADEV SOLUTIONS, CNPJ 59.198.345/0001-44</strong>. A plataforma permite encontrar lojas, consultar catálogos, montar carrinhos e organizar pedidos, inclusive para encaminhamento pelo WhatsApp.</p>
<p>Os produtos são ofertados pelas lojas identificadas no catálogo. A plataforma fornece os recursos tecnológicos e responde por sua atuação nos limites da legislação. As lojas respondem pelas informações de suas ofertas e pelo atendimento que realizam. Esta divisão não exclui responsabilidades legalmente atribuídas a qualquer participante.</p>
<p>Estes termos se aplicam às funcionalidades disponibilizadas. Condições comerciais de contratação do sistema pelas lojas, como planos e cobrança, devem constar da proposta ou contrato específico; esta página não cria uma assinatura ou cobrança por si só.</p>
<p>Contato: <a className="email" href="mailto:backupvemdedelivery@gmail.com">backupvemdedelivery@gmail.com</a>. O tratamento de dados é descrito na <a href="/privacidade/">Política de Privacidade</a>.</p></section>
<section id="conta"><h2>2. Conta, credenciais e acesso</h2>
<p>Algumas funções exigem cadastro e validação de e-mail ou WhatsApp. Informe dados corretos, mantenha seus contatos atualizados e utilize apenas números e endereços eletrônicos que estejam sob seu controle.</p>
<p>Proteja sua senha e os códigos de autenticação. Avise o suporte se suspeitar de acesso indevido. A existência de uma ação na conta não impede a apuração de fraude ou de falha de segurança.</p>
<p>Para contratar, o usuário deve ter capacidade legal ou a assistência/representação exigida. Produtos com restrição etária, como bebidas alcoólicas, somente podem ser adquiridos por quem atende à idade legal; a loja deve cumprir as verificações e restrições aplicáveis.</p></section>
<section id="pedidos"><h2>3. Catálogo, preços e confirmação do pedido</h2>
<p>Antes de confirmar, confira a loja, os produtos, quantidades, adicionais, observações, endereço, descontos, taxa de entrega e total. As lojas podem definir horários, dias de disponibilidade, limites de quantidade e condições de atendimento.</p>
<p>O sistema revalida os itens e valores durante o checkout. Se detectar alteração, poderá atualizar o carrinho, solicitar nova conferência ou impedir a conclusão de item indisponível. Esse procedimento não afasta os direitos relacionados à oferta e ao pedido já contratado.</p>
<div className="callout"><strong>Abrir o WhatsApp não envia a mensagem automaticamente.</strong> No fluxo pelo WhatsApp, você precisa enviá-la e acompanhar a resposta da loja. A geração de um registro na plataforma ou a abertura do aplicativo não comprova, por si só, o recebimento ou aceite da loja.</div>
<p>Cupons dependem das condições exibidas, como valor mínimo, período, público e limite de usos. Na revisão do pedido, um benefício pode ficar temporariamente reservado; editar ou expirar a revisão libera essa reserva conforme as regras do sistema. O encaminhamento ao WhatsApp pode registrar a utilização.</p>
<p>Lojas identificadas como demonstração apresentam exemplos para testes. Não efetue pagamentos por produtos demonstrativos sem confirmar que existe uma oferta real e um fornecedor responsável.</p></section>
<section id="pagamentos"><h2>4. Pagamento, entrega e retirada</h2>
<p>No fluxo atual pelo WhatsApp, escolher uma forma de pagamento no checkout apenas informa sua preferência. O pagamento e sua confirmação são combinados com a loja. A plataforma não deve ser interpretada como comprovante de pagamento somente por registrar um pedido.</p>
<p>Confira o destinatário e as instruções de pagamento antes de transferir valores. A loja deve informar as condições de entrega ou retirada e eventuais alterações que afetem o atendimento. O cliente deve fornecer endereço e contato adequados para a comunicação.</p>
<p>Se uma modalidade de pagamento online for disponibilizada futuramente, seu prestador e suas condições deverão ser informados no fluxo correspondente antes da contratação.</p></section>
<section id="atendimento"><h2>5. Cancelamentos, problemas e atendimento</h2>
<p>Para informar produto incorreto, atraso, problema de qualidade, necessidade de cancelamento ou reembolso, entre em contato com a loja pelos canais do pedido. Para falhas da plataforma ou dificuldade de atendimento, escreva para <a className="email" href="mailto:backupvemdedelivery@gmail.com">backupvemdedelivery@gmail.com</a>, informando a loja, o número do pedido e o ocorrido.</p>
<p>As solicitações serão avaliadas considerando a oferta, a etapa do atendimento e a legislação aplicável. Direitos de arrependimento, garantia, reparação e reembolso, quando cabíveis, permanecem assegurados. Não há renúncia a direitos do consumidor nem exigência de resolver a questão exclusivamente com a loja.</p>
<p>As condições específicas de cada oferta devem ser apresentadas antes da contratação. Estes termos não estabelecem uma regra genérica de “sem devolução” para todos os produtos.</p></section>
<section id="lojas"><h2>6. Responsabilidades das lojas</h2>
<ul>
<li>Manter identificação, contatos, catálogo, preços, adicionais, disponibilidade, horários e regiões atendidas corretos.</li>
<li>Informar características relevantes, restrições, riscos e, quando pertinente, ingredientes e alergênicos dos produtos.</li>
<li>Ofertar somente produtos permitidos e cumprir as exigências fiscais, sanitárias, profissionais e de proteção ao consumidor aplicáveis.</li>
<li>Atender os pedidos recebidos, comunicar problemas e tratar solicitações de consumidores.</li>
<li>Usar os dados recebidos de clientes para finalidades legítimas ligadas ao atendimento, respeitando a legislação de proteção de dados.</li>
<li>Publicar apenas conteúdo e imagens próprios ou que tenham autorização para utilizar.</li>
</ul>
<p>O acesso ao painel deve ser restrito às pessoas autorizadas pela loja. O conteúdo de uma loja não deve ser usado para acessar dados ou administrar outra loja.</p></section>
<section id="uso"><h2>7. Uso permitido e proteção do serviço</h2>
<p>Não é permitido usar a plataforma para fraude, pedidos falsos, divulgação de conteúdo ilícito, tentativa de acessar dados de terceiros, exploração de vulnerabilidades, coleta abusiva de informações ou interferência no funcionamento do serviço.</p>
<p>Podemos aplicar limites de acesso e restrições proporcionais para proteger usuários e investigar abuso, com possibilidade de solicitar revisão pelo contato informado. Quando possível e adequado à segurança, serão informados o motivo e as orientações para regularização.</p>
<p>A marca e os elementos próprios do VemDeDelivery permanecem vinculados aos seus titulares. O uso normal da plataforma não transfere direitos de propriedade intelectual nem autoriza reproduzir catálogos de terceiros.</p></section>
<section id="disponibilidade"><h2>8. Disponibilidade e serviços de terceiros</h2>
<p>O serviço pode passar por manutenção ou sofrer interrupções. Seu funcionamento também depende de conexão, hospedagem e serviços como e-mail e WhatsApp. O suporte avaliará os problemas comunicados e as providências cabíveis.</p>
<p>Não prometemos disponibilidade ininterrupta ou ausência absoluta de falhas. Essa informação não exclui obrigações legais, compromissos expressamente contratados ou responsabilidade por defeitos do serviço.</p>
<p>Para encerrar sua conta ou solicitar análise da exclusão de dados, entre em contato pelo canal indicado na Política de Privacidade. A conservação de registros será avaliada conforme a finalidade e as obrigações aplicáveis.</p></section>
<section id="backups"><h2>9. VemDeDelivery Backups e Google Drive</h2>
<p><strong>VemDeDelivery Backups</strong> é a integração administrativa destinada à continuidade da operação, não um serviço público de armazenamento de arquivos. Seu acesso ao Google Drive depende da autorização do titular da conta de backups e fica limitado às permissões concedidas.</p>
<p>Quando habilitada, a integração envia, verifica e recupera cópias de segurança no destino configurado. A autorização não transfere propriedade dos dados à plataforma ou torna os arquivos públicos. O administrador deve proteger credenciais, chaves de criptografia e meios de recuperação da conta.</p>
<p>A revogação da conexão Google interrompe o acesso autorizado e pode impedir novos backups ou restaurações a partir do Drive. Arquivos já armazenados não são removidos automaticamente. Os critérios de tratamento e as formas de revogação e exclusão estão na <a href="/privacidade/#google">seção de backups da Política de Privacidade</a>.</p></section>
<section id="alteracoes"><h2>10. Atualizações, legislação e contato</h2>
<p>Estes termos poderão ser atualizados conforme mudanças no serviço. A data e a versão ficam no início da página. Alterações relevantes serão comunicadas pelos canais disponíveis, respeitando condições já contratadas e a necessidade de aceite específico quando aplicável.</p>
<p>Aplica-se a legislação brasileira, preservados os direitos e as regras de competência que protegem o consumidor. Estes termos não impõem foro exclusivo que impeça o exercício de direitos.</p>
<p><strong>COBRADEV SOLUTIONS — CNPJ 59.198.345/0001-44</strong><br/>Contato para assuntos da plataforma e da integração de backups: <a className="email" href="mailto:backupvemdedelivery@gmail.com">backupvemdedelivery@gmail.com</a>.</p>
<p className="source">Referências: <a href="https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm">Código de Defesa do Consumidor</a> e <a href="https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/decreto/d7962.htm">Decreto nº 7.962/2013</a>.</p></section>
</>;}
function Privacy() {return <>
<section id="responsavel"><h2>1. Quem somos e a quem esta política se aplica</h2>
<p>O <strong>VemDeDelivery</strong> é uma plataforma de divulgação de lojas, consulta de produtos e organização de pedidos, mantida pela <strong>COBRADEV SOLUTIONS, CNPJ 59.198.345/0001-44</strong>. Esta política abrange visitantes, clientes, representantes de lojas e a integração administrativa <strong>VemDeDelivery Backups</strong>.</p>
<p>A COBRADEV SOLUTIONS decide como tratar dados de contas, segurança e funcionamento da plataforma. Cada loja também trata os dados que recebe para atender pedidos, organizar entregas e cumprir suas obrigações. As responsabilidades de cada participante dependem da operação realizada; esta política não substitui as informações de privacidade da loja.</p>
<p>Contato para privacidade: <a className="email" href="mailto:backupvemdedelivery@gmail.com">backupvemdedelivery@gmail.com</a>.</p></section>
<section id="dados"><h2>2. Quais dados tratamos e para quê</h2>
<div className="table-wrap"><table><thead><tr><th>Categoria</th><th>Dados e utilização</th></tr></thead><tbody>
<tr><td>Conta e identificação</td><td>Nome, nome de usuário, e-mail, telefone/WhatsApp e informações de verificação, para criar a conta, autenticar acessos, recuperar credenciais e atualizar contatos. Senhas são armazenadas em formato de hash.</td></tr>
<tr><td>Pedidos e atendimento</td><td>Produtos, quantidades, adicionais, observações, valores, cupons, forma de pagamento escolhida e histórico, para montar, revisar e acompanhar pedidos e atender solicitações.</td></tr>
<tr><td>Entrega e localização</td><td>CEP, endereço, número, complemento, bairro, cidade, UF e referências, para identificar atendimento e taxa de entrega. Coordenadas podem ser utilizadas quando você autoriza a localização no navegador.</td></tr>
<tr><td>Lojas</td><td>Dados dos responsáveis e da conta administrativa, contato comercial, catálogo, imagens, horários e regiões atendidas, para disponibilizar a loja e seu painel.</td></tr>
<tr><td>Segurança e funcionamento</td><td>Endereço IP, data e hora, identificadores de sessão e requisição, registros de autenticação e de erros, para prevenir abuso, investigar incidentes e manter o serviço.</td></tr>
</tbody></table></div>
<p>No fluxo atual pelo WhatsApp, a plataforma registra a <strong>forma de pagamento escolhida</strong>; esse registro não é um processamento de cartão. Não informe número completo de cartão, código de segurança, senhas ou códigos OTP nas observações do pedido.</p>
<p>Evite inserir dados sensíveis ou informações de terceiros desnecessárias em campos livres. As observações adicionadas ao pedido podem ser vistas pela loja e fazer parte de seus registros.</p></section>
<section id="fundamentos"><h2>3. Fundamentos do tratamento</h2>
<p>Conforme a finalidade, o tratamento se apoia na execução de contratos ou procedimentos solicitados por você, no cumprimento de obrigações legais, no exercício de direitos ou no interesse legítimo em segurança e funcionamento, considerando seus direitos. Quando o tratamento depender de consentimento, ele será solicitado de forma específica e poderá ser revogado. A leitura desta política não representa consentimento genérico para qualquer uso de dados.</p></section>
<section id="compartilhamento"><h2>4. Com quem os dados são compartilhados</h2>
<ul>
<li><strong>Loja escolhida:</strong> recebe os dados necessários ao pedido e à entrega. Ao abrir o WhatsApp, os dados são preparados em uma mensagem; o envio depende da sua ação nesse aplicativo.</li>
<li><strong>Infraestrutura e comunicações:</strong> utilizamos hospedagem da Hostinger, serviços de e-mail como SendPulse e a integração Evolution API/WhatsApp para validações e comunicações operacionais.</li>
<li><strong>Localização:</strong> recursos de consulta de CEP e geocodificação podem consultar provedores externos. Quando a geocodificação está habilitada, coordenadas podem ser encaminhadas ao provedor configurado, como Nominatim/OpenStreetMap.</li>
<li><strong>Diagnóstico:</strong> serviços de monitoramento, quando habilitados, podem receber dados técnicos de erros e desempenho para suporte à operação.</li>
<li><strong>Backup:</strong> cópias do banco e da mídia são mantidas para recuperação. A seção seguinte descreve a integração administrativa com Google Drive.</li>
<li><strong>Solicitações legais:</strong> informações podem ser fornecidas quando houver fundamento jurídico e necessidade de atender uma obrigação ou proteger direitos.</li>
</ul>
<p>Fornecedores podem manter infraestrutura em outros países. O tratamento internacional exige as salvaguardas aplicáveis à operação. Você pode solicitar esclarecimentos sobre fornecedores e transferências pelo contato desta política.</p></section>
<section id="google"><h2>5. Google Drive e VemDeDelivery Backups</h2>
<div className="callout"><strong>A conta Google conectada é a conta administrativa de backups.</strong> Clientes e lojistas não precisam autorizar acesso ao próprio Google Drive para usar o VemDeDelivery.</div>
<p>A integração <strong>VemDeDelivery Backups</strong>, quando habilitada, utiliza o rclone para guardar e recuperar cópias de segurança em uma conta Google autorizada pelo administrador. O acesso é solicitado com o escopo <code>drive.file</code>, limitado aos arquivos e pastas criados ou autorizados para o aplicativo.</p>
<p>A integração acessa conteúdo e metadados desses arquivos — como nome, identificador, tamanho e dados necessários à verificação de integridade — para enviar, listar, conferir e recuperar backups. Esses backups podem conter dados de contas, pedidos, lojas e imagens descritos nesta política. O envio ao Drive deve ocorrer pelo destino criptografado configurado para essa finalidade.</p>
<p>Credenciais e tokens OAuth ficam na configuração protegida da ferramenta, para permitir acesso sem solicitar a senha Google a cada execução. Eles não são exibidos aos clientes da plataforma. As chaves de recuperação da criptografia devem ser guardadas pelo administrador em local seguro separado do servidor.</p>
<p>Os dados obtidos por meio das APIs do Google são utilizados somente para as funções de backup e recuperação informadas. Não são vendidos, utilizados para publicidade personalizada, avaliação de crédito ou treinamento de modelos de inteligência artificial de uso geral. Acesso humano fica restrito às situações necessárias e permitidas para suporte autorizado, segurança ou cumprimento de obrigação legal.</p>
<p>O uso e a transferência de informações recebidas das APIs do Google seguem a <a href="https://developers.google.com/terms/api-services-user-data-policy">Política de Dados do Usuário dos Serviços de API do Google</a>, incluindo os requisitos de <em>Uso Limitado</em>, quando aplicáveis.</p>
<h3>Como revogar e excluir</h3>
<p>O administrador pode revogar a autorização em <a href="https://myaccount.google.com/connections">Conexões da Conta Google</a>. A revogação impede novos acessos autorizados, mas não remove automaticamente arquivos já enviados nem as cópias locais. A exclusão dos arquivos deve ser realizada no Drive, incluindo a lixeira quando cabível, e nas cópias mantidas pelo administrador, respeitadas as necessidades legais de conservação. Clientes podem solicitar a exclusão de seus dados pelo canal de privacidade abaixo.</p></section>
<section id="cookies"><h2>6. Cookies, preferências e localização</h2>
<p>Usamos cookies de sessão e de proteção contra requisições indevidas, além de armazenamento do navegador para preferências como tema visual. Sessões também permitem manter o carrinho e o local de entrega. Desativar esses recursos pode impedir login, carrinho ou outras funções essenciais.</p>
<p><strong>Divulgação comercial e Analytics:</strong> nas páginas para lojistas, as métricas do Google (Analytics/Tag Manager) só carregam após a escolha "Aceitar métricas". O visitante pode recusar ou alterar a escolha no rodapé da página. Com autorização, podemos guardar os parâmetros de campanha (UTM, gclid/gbraid/wbraid) e um identificador técnico do Analytics para entender como a campanha levou à contratação. Ao clicar para falar com nossa equipe, a mensagem do WhatsApp inclui uma referência curta; essa referência operacional permite que a equipe associe voluntariamente o atendimento a uma loja no Superadmin mesmo sem cookies de publicidade. O clique não significa que a conversa foi enviada. Nenhum conteúdo da conversa, telefone ou e-mail é encaminhado ao GA4 por esse mecanismo.</p>
<p>A localização do navegador depende da permissão que você concede e pode ser desativada nas configurações do dispositivo. Quando disponível, você pode informar cidade ou endereço manualmente. A permissão técnica do navegador não autoriza usos diferentes dos descritos aqui.</p>
<p>O carregamento de recursos externos, como bibliotecas de interface, pode transmitir dados técnicos da conexão ao respectivo fornecedor. A adoção de novas finalidades, como publicidade comportamental, exige informação e tratamento adequado antes de sua utilização.</p></section>
<section id="retencao"><h2>7. Segurança, conservação e eliminação</h2>
<p>Empregamos controle de acesso por loja, proteção de senhas, validação de contatos, limites de tentativas e registros de segurança. Backups e testes de restauração apoiam a recuperação de dados. Essas medidas reduzem riscos, mas não tornam qualquer sistema imune a incidentes.</p>
<p>Os dados são conservados conforme a finalidade, a relação com o usuário e as necessidades legais ou de defesa de direitos. O encerramento da conta não elimina automaticamente registros cuja conservação seja necessária. Informações sem finalidade de conservação devem ser eliminadas ou anonimizadas.</p>
<p>Backups seguem a retenção configurada na operação e podem manter dados até sua substituição ou exclusão. Uma solicitação de eliminação exige avaliar também as cópias de segurança; não prometemos apagamento instantâneo de todas as cópias. Os critérios e prazos aplicáveis ao seu caso podem ser solicitados pelo canal abaixo.</p></section>
<section id="direitos"><h2>8. Seus direitos e como exercê-los</h2>
<p>Você pode solicitar confirmação e acesso aos dados, correção, informações sobre compartilhamento e, quando cabível, portabilidade, anonimização, bloqueio, eliminação, oposição ou revogação do consentimento. Cada solicitação será analisada conforme seus requisitos legais.</p>
<p>Envie a solicitação para <a className="email" href="mailto:backupvemdedelivery@gmail.com">backupvemdedelivery@gmail.com</a>, indicando o e-mail ou telefone da conta e o pedido desejado. Podemos solicitar confirmação de identidade proporcional à necessidade, para evitar acesso ou exclusão por terceiros. Não envie senhas ou códigos de autenticação.</p>
<p>Se a demanda envolver tratamento realizado por uma loja, auxiliaremos no direcionamento ao responsável. Se o atendimento não resolver a questão, você pode recorrer à <a href="https://www.gov.br/pt-br/servicos/abrir-requerimento-relacionado-a-lgpd">ANPD</a> e aos demais órgãos competentes.</p></section>
<section id="menores"><h2>9. Crianças e adolescentes</h2>
<p>A plataforma não é dirigida a crianças. O uso por adolescentes deve observar a capacidade legal, a participação de responsáveis quando necessária e as restrições dos produtos. Se identificar uso indevido de dados de criança ou adolescente, entre em contato para avaliação e providências voltadas ao seu melhor interesse.</p></section>
<section id="contato"><h2>10. Contato e atualizações</h2>
<p><strong>COBRADEV SOLUTIONS — CNPJ 59.198.345/0001-44</strong><br/>Canal de privacidade e integração Google: <a className="email" href="mailto:backupvemdedelivery@gmail.com">backupvemdedelivery@gmail.com</a>.</p>
<p>Esta política poderá ser atualizada para refletir mudanças no serviço. A versão e a data ficam no início da página. Mudanças relevantes nas finalidades ou permissões serão informadas pelos canais disponíveis, com nova autorização quando necessária.</p>
<p className="source">Referência legal: <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm">Lei Geral de Proteção de Dados Pessoais</a>. Veja também os <a href="/termos/">Termos de Serviço</a>.</p></section>
</>;}
function TermsIntro() {return <><p>Regras para utilizar o VemDeDelivery, consultar lojas e organizar pedidos com clareza e segurança.</p><p>Versão 1.0 · Atualização: 2 de setembro de 2026</p><nav aria-label="Índice do documento">
<a href="#plataforma">1. Plataforma e responsável</a><a href="#conta">2. Conta e acesso</a><a href="#pedidos">3. Produtos e pedidos</a><a href="#pagamentos">4. Pagamento e entrega</a><a href="#atendimento">5. Cancelamentos e atendimento</a><a href="#lojas">6. Responsabilidades das lojas</a><a href="#uso">7. Uso permitido</a><a href="#disponibilidade">8. Disponibilidade</a><a href="#backups">9. Integração de backups</a><a href="#alteracoes">10. Alterações e contato</a>
</nav></>;}
function PrivacyIntro() {return <><p>Como tratamos dados ao conectar pessoas e lojas — e como a integração VemDeDelivery Backups utiliza o Google Drive.</p><p>Versão 1.0 · Atualização: 2 de setembro de 2026</p><nav aria-label="Índice do documento">
<a href="#responsavel">1. Quem somos</a><a href="#dados">2. Dados e finalidades</a><a href="#fundamentos">3. Fundamentos</a><a href="#compartilhamento">4. Compartilhamento</a><a href="#google">5. Google Drive e backups</a><a href="#cookies">6. Cookies e localização</a><a href="#retencao">7. Segurança e conservação</a><a href="#direitos">8. Seus direitos</a><a href="#menores">9. Crianças e adolescentes</a><a href="#contato">10. Contato e atualizações</a>
</nav></>;}
export function LegalPage({page}:{page:string}) {return page === "terms" ? <><TermsIntro/><Terms/></> : <><PrivacyIntro/><Privacy/></>;}
