import { useEffect, useState } from "react";
import { Analytics } from "./Analytics";
import { Marketplace } from "./Marketplace";
import { Landing, SEOPage } from "./Marketing";
import { Catalog, Cart, Checkout, Review } from "./Commerce";
import { LegalPage } from "./legalContent";
export type PageData = any;
export function CSRF({ data }: { data: PageData }) { return <input type="hidden" name="csrfmiddlewaretoken" value={data.csrf} />; }
export function PostButton({ data, action, children, name, value }: any) { return <form method="post" action={action}><CSRF data={data} /><button name={name} value={value}>{children}</button></form>; }
const money = (v: any) => Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
function FormFields({ form }: any) {
  return <>{form.errors.map((e: string, n: number) => <p key={n} role="alert">{e}</p>)}{form.fields.map((f: any) => <label key={f.name} className="public-field">{f.label}{f.required && " *"}
    {f.choices?.length ? <select name={f.name} defaultValue={f.value} required={f.required}>{f.choices.map((c: any) => <option key={c.value} value={c.value}>{c.label}</option>)}</select> : f.kind === "textarea" ? <textarea name={f.name} defaultValue={f.value} required={f.required} /> : <input id={`id_${f.name}`} type={f.kind} name={f.name} defaultValue={f.kind === "checkbox" ? "on" : f.value} defaultChecked={f.kind === "checkbox" ? Boolean(f.value) : undefined} required={f.required} maxLength={f.max_length || undefined} autoComplete={f.autocomplete} aria-invalid={Boolean(f.errors.length)} />}
    {f.errors.map((e: string, n: number) => <small role="alert" key={n}>{e}</small>)}
  </label>)}</>;
}
function Verify({ data }: any) {
  const p = data.props.pending; const contact = data.page === "verify-contact";
  const [seconds, setSeconds] = useState(data.props.resend_seconds || 0);
  useEffect(() => { if (!seconds) return; const t = setTimeout(() => setSeconds(seconds - 1), 1000); return () => clearTimeout(t); }, [seconds]);
  return <section className="public-card"><p>{contact ? "Seu contato atual continua válido até a confirmação." : p.channel === "email" ? "Etapa 1 de 2 · E-mail" : "Etapa 2 de 2 · WhatsApp"}</p><p>Digite o código enviado para <strong>{p.destination}</strong>.</p><form method="post"><CSRF data={data}/><input type="hidden" name="channel" value={p.channel}/><input type="hidden" name="action" value="verify"/><label className="public-field">Código de verificação<input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} required /></label><button>{contact ? "Confirmar e atualizar contato" : p.channel === "email" ? "Confirmar e-mail" : "Confirmar e criar conta"}</button></form><form method="post"><CSRF data={data}/><input type="hidden" name="channel" value={p.channel}/><button name="action" value="send" disabled={seconds > 0}>Reenviar código{seconds ? ` (${seconds}s)` : ""}</button></form>{contact && <PostButton data={data} name="action" value="cancel">Cancelar esta alteração</PostButton>}<small>O código vale por 10 minutos. Aguarde 60 segundos entre os envios.</small><p><a href={contact ? "/conta/dados/" : "/conta/criar-conta/"}>{contact ? "Voltar aos meus dados" : "Corrigir dados e reiniciar cadastro"}</a></p></section>;
}
export function OrderSummary({ order, data }: any) {
  return <section className="public-card"><h2>Pedido #{order.id}</h2>{order.scheduled_for&&<p>Agendado: {new Date(order.scheduled_for).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}</p>}<p>{order.store_name} · {order.created_label}</p><p>{order.status_label}</p>{order.items?.map((item: any) => <div key={item.id} className="public-item"><strong>{item.quantity}× {item.name}</strong><span>{money(item.total)}</span>{item.details?.map((line: string, n: number) => <small key={n}>{line}</small>)}{item.notes && <p>Observações: {item.notes}</p>}</div>)}<p>{order.delivery_label} · {order.delivery_address}</p><p>{order.payment_label}</p><p>Subtotal: {money(order.subtotal)} · Entrega: {money(order.delivery_fee)}</p>{Number(order.discount_amount) > 0 && <p>Desconto: {money(order.discount_amount)} ({order.coupon_code})</p>}<strong>Total: {money(order.total)}</strong>{order.repeat_url && <PostButton data={data} action={order.repeat_url}>Repetir pedido</PostButton>}</section>;
}
function Accounts({ data }: any) {
  const p = data.props;
  if (data.page.startsWith("verify-")) return <Verify data={data}/>;
  if (p.form) return <section className="public-card"><form method="post"><CSRF data={data}/><input type="hidden" name="next" value={p.next || "/"}/><FormFields form={p.form}/><button>{p.submit_label || "Salvar"}</button></form>{data.page === "login" && <p><a href="/conta/recuperar-senha/">Esqueci minha senha</a> · <a href="/conta/criar-conta/">Criar conta</a></p>}{p.pending_changes?.length > 0 && <h2>Confirmação de contato pendente</h2>}{p.pending_changes?.map((change: any) => <p key={change.id}>Confirme seu novo {change.label}: <a href={change.url}>{change.destination}</a></p>)}</section>;
  if (data.page === "account") return <><p>Olá, {data.user.name}!</p><p>{p.orders_count} pedidos · {p.addresses_count} endereços</p><nav className="public-grid"><a className="public-card" href="/conta/pedidos/">Meus pedidos</a><a className="public-card" href="/conta/enderecos/">Meus endereços</a><a className="public-card" href="/conta/dados/">Meus dados</a><a className="public-card" href="/conta/alterar-senha/">Alterar senha</a></nav>{p.last_order && <OrderSummary order={p.last_order} data={data}/>}</>;
  if (data.page === "addresses") return <><a href="/conta/enderecos/novo/">Adicionar endereço</a><div className="public-grid">{p.addresses.map((a: any) => <section className="public-card" key={a.id}><h2>{a.label} {a.is_default && "· Principal"}</h2><p>{a.street}, {a.number} {a.complement}</p><p>{a.neighborhood} — {a.city}/{a.state}</p><p>CEP {a.zip_code}</p>{a.reference && <p>Referência: {a.reference}</p>}<a href={`/conta/enderecos/${a.id}/editar/`}>Editar</a>{!a.is_default && <PostButton data={data} action={`/conta/enderecos/${a.id}/principal/`}>Tornar principal</PostButton>}<PostButton data={data} action={`/conta/enderecos/${a.id}/excluir/`}>Excluir</PostButton></section>)}</div>{!p.addresses.length && <p>Nenhum endereço cadastrado.</p>}</>;
  if (data.page === "orders") return <>{p.orders.map((o: any) => <article className="public-card" key={o.id}><a href={o.detail_url}><h2>Pedido #{o.id}</h2></a><p>{o.store_name} · {o.created_label} · {o.status_label}</p><strong>{money(o.total)}</strong></article>)}{!p.orders.length && <p>Nenhum pedido encontrado.</p>}{p.pagination && <nav>{p.pagination.previous && <a href={`?page=${p.pagination.previous}`}>Anterior</a>} Página {p.pagination.page} {p.pagination.next && <a href={`?page=${p.pagination.next}`}>Próxima</a>}</nav>}</>;
  if (data.page === "order") return <OrderSummary order={p.order} data={data}/>;
  return <section className="public-card"><p>{p.message}</p><a href="/conta/entrar/">Entrar na minha conta</a></section>;
}
export function PublicApp({ data }: { data: PageData }) {
  if (data.page === "landing") return <Landing data={data}/>;
  if (data.page === "seo") return <SEOPage data={data}/>;
  if (data.page === "feedback") return <main className="public-main"><h1>Sua opinião e preferências</h1>{data.props.done?<p>Obrigado! Sua preferência foi registrada.</p>:<>{data.props.kind === "feedback"&&<form method="post"><CSRF data={data}/><label>Nota<select name="rating" required>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Comentário<textarea name="comment" maxLength={1000}/></label><button>Enviar avaliação</button></form>}<form method="post"><CSRF data={data}/><button name="action" value="unsubscribe">Deixar de receber mensagens de marketing desta loja</button></form></>}</main>;
  const commerce = data.page === "marketplace" ? <Marketplace data={data}/> : data.page === "catalog" ? <Catalog data={data}/> : data.page === "cart" ? <Cart data={data}/> : data.page === "checkout" ? <Checkout data={data}/> : ["review","payment"].includes(data.page) ? <Review data={data}/> : null;
  const b=data.store?.brand||{};
  const theme:any={};
  for(const key of ["primary_color","secondary_color","accent_color","background_color","card_background_color","text_color","muted_text_color","border_color","button_text_color"]) if(/^#[0-9a-f]{6}$/i.test(b[key]||""))theme[`--${key.replaceAll("_","-")}`]=b[key];
  return <div className="public-shell" style={theme}><a className="vdd-skip" href="#vdd-content">Ir para o conteúdo</a><header className="vdd-header"><div className="vdd-container vdd-header-inner"><a className="vdd-logo" href={data.home_url}><img src={data.store?.logo || "/static/images/brand/logo-vemdedelivery.svg"} alt={data.store?.name || "VemDeDelivery"} width="365" height="72"/></a><nav className="vdd-nav">{data.store && <><a href="/">{data.store.name}</a><a href="/checkout/cart/">Carrinho</a></>}{data.user.authenticated ? <><a href="/conta/">Minha conta</a><a href="/meus-pedidos/">Meus pedidos</a><PostButton data={data} action="/conta/sair/">Sair</PostButton></> : <><a href="/conta/entrar/">Entrar</a><a href="/conta/criar-conta/">Criar conta</a></>}</nav></div></header><main id="vdd-content" className={`public-main page-${data.page}`}><h1>{data.heading}</h1><Analytics data={data}/>{data.messages.map((m: any, n: number) => <p key={n} className={`public-notice ${m.level}`} role="status">{m.text}</p>)}{data.page === "terms" || data.page === "privacy" ? <LegalPage page={data.page}/> : commerce || <Accounts data={data}/>}</main><footer className="vdd-footer"><div className="vdd-container"><strong>COBRADEV SOLUTIONS</strong><p>CNPJ 59.198.345/0001-44</p><a href="/termos/">Termos de Serviço</a> · <a href="/privacidade/">Política de Privacidade</a><p>© {data.year} VemDeDelivery</p></div></footer></div>;
}
