# Generated by Django 5.2.12 on 2026-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branding", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brandconfig",
            name="custom_domain",
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="logo",
            field=models.ImageField(
                blank=True,
                upload_to="logos/",
                verbose_name="Logo da loja (recomendada: 200x200px)",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="primary_color",
            field=models.CharField(
                default="#000000",
                max_length=7,
                verbose_name="Cor principal (botões, links)",
            ),
        ),
        migrations.AlterField(
            model_name="brandconfig",
            name="secondary_color",
            field=models.CharField(
                default="#FFFFFF",
                max_length=7,
                verbose_name="Cor secundária (headers, ícones)",
            ),
        ),
    ]
