"""Conteúdo editorial das páginas públicas de aquisição e SEO.

O conteúdo fica fora das views para tornar revisão comercial/SEO simples e para
impedir páginas geradas a partir de parâmetros livres. Cada URL indexável é
explicitamente cadastrada e possui conteúdo próprio.
"""

PRICE = "149.00"
PRICE_LABEL = "R$ 149/mês"


def _page(
    *,
    path,
    name,
    title,
    description,
    eyebrow,
    h1,
    highlight,
    lead,
    section_title,
    section_text,
    benefits,
    examples,
    faq,
    group,
    related=(),
):
    return {
        "path": path,
        "name": name,
        "title": title,
        "description": description,
        "eyebrow": eyebrow,
        "h1": h1,
        "highlight": highlight,
        "lead": lead,
        "section_title": section_title,
        "section_text": section_text,
        "benefits": benefits,
        "examples": examples,
        "faq": faq,
        "group": group,
        "related": related,
    }


MARKETING_PAGES = {
    "cardapio-online": _page(
        path="cardapio-online/", name="cardapio_online",
        title="Cardápio online para delivery e lojas | VemDeDelivery",
        description="Crie um cardápio ou catálogo online com sua marca, produtos, adicionais, entrega, retirada e pedidos pelo WhatsApp. Sem comissão do VemDeDelivery por pedido.",
        eyebrow="CARDÁPIO E CATÁLOGO ONLINE",
        h1="Seu catálogo online, organizado para",
        highlight="virar pedido",
        lead="Publique produtos, fotos, preços e opções em um link próprio da sua loja. O cliente acessa pelo navegador, monta o pedido e pode continuar a experiência pelo WhatsApp.",
        section_title="Mais do que uma lista de produtos",
        section_text="Um bom catálogo reduz perguntas repetidas e deixa claro o que está disponível, quanto custa e como o cliente pode receber. O VemDeDelivery reúne vitrine, carrinho e operação em uma experiência pensada para comércio local.",
        benefits=(
            ("Sua identidade", "Use logo, cores, banner e informações da loja para apresentar sua marca, não a marca de um marketplace."),
            ("Produtos bem explicados", "Organize categorias, fotos, descrições, preços, opções e adicionais para facilitar a escolha."),
            ("Pedido com contexto", "Entrega, retirada, horários e áreas atendidas fazem parte da configuração da loja e ajudam o cliente a concluir o pedido."),
        ),
        examples=("Link na bio do Instagram", "QR Code no balcão ou embalagem", "Campanhas no Google, Meta e WhatsApp", "Atendimento que consulta o mesmo catálogo"),
        faq=(
            ("Meu cliente precisa instalar aplicativo?", "Não. A loja abre no navegador do celular ou computador por um link próprio."),
            ("Posso usar para produtos com opções?", "Sim. O catálogo suporta opções e adicionais, e há recursos específicos para operações como pizza meio a meio."),
            ("Serve apenas para restaurantes?", "Não. A estrutura também atende mercados, mercearias, pet shops, casas de ração, floriculturas e outros comércios locais com catálogo e pedidos."),
        ),
        group="Soluções", related=("pedidos-pelo-whatsapp", "agente-whatsapp-delivery", "delivery-sem-comissao", "loja-online-comercio-local"),
    ),
    "delivery-sem-comissao": _page(
        path="delivery-sem-comissao/", name="delivery_sem_comissao",
        title="Delivery sem comissão por pedido | VemDeDelivery",
        description="Tenha um canal próprio de pedidos por mensalidade fixa, sem comissão do VemDeDelivery sobre cada pedido. Cardápio online, WhatsApp, painel e agente de atendimento.",
        eyebrow="CANAL PRÓPRIO DE VENDAS",
        h1="Delivery sem comissão do VemDeDelivery",
        highlight="sobre seus pedidos",
        lead="Em vez de pagar uma porcentagem ao VemDeDelivery a cada venda, sua loja usa uma assinatura e mantém um canal próprio para divulgar o catálogo e receber pedidos.",
        section_title="Mais previsibilidade para o canal direto",
        section_text="Marketplaces podem continuar fazendo parte da sua estratégia. O VemDeDelivery cria outra opção: um endereço próprio para clientes recorrentes, campanhas e divulgação direta, com custo de plataforma previsível.",
        benefits=(
            ("Mensalidade previsível", "O plano mensal parte de R$ 149 e o VemDeDelivery não aplica comissão percentual sobre o valor dos pedidos."),
            ("Cliente perto da sua marca", "O pedido acontece na experiência da sua loja, com identidade, catálogo e WhatsApp próprios."),
            ("Use junto com outros canais", "Você não precisa abandonar marketplaces ou redes sociais; o canal próprio pode complementar sua operação."),
        ),
        examples=("Clientes recorrentes", "Cupons e campanhas próprias", "Tráfego pago para o link da loja", "Pedidos vindos do WhatsApp"),
        faq=(
            ("Existe comissão por pedido?", "O VemDeDelivery não cobra comissão percentual sobre os pedidos. Meios de pagamento online, quando usados, podem cobrar tarifas próprias."),
            ("Preciso sair dos marketplaces?", "Não. A proposta é dar à loja um canal próprio adicional, que pode conviver com os demais canais de venda."),
            ("Quais planos existem?", "A estrutura comercial prevê planos mensal, trimestral, semestral e anual, com descontos nos períodos maiores."),
        ),
        group="Soluções", related=("cardapio-online", "pedidos-pelo-whatsapp", "sistema-para-restaurante", "sistema-para-mercado"),
    ),
    "pedidos-pelo-whatsapp": _page(
        path="pedidos-pelo-whatsapp/", name="pedidos_pelo_whatsapp",
        title="Pedidos pelo WhatsApp com catálogo online | VemDeDelivery",
        description="Receba pedidos pelo WhatsApp da sua loja com catálogo, carrinho, entrega ou retirada e apoio de agente de atendimento. Conheça o VemDeDelivery.",
        eyebrow="WHATSAPP COMO CANAL DE PEDIDOS",
        h1="Transforme conversas no WhatsApp em",
        highlight="pedidos organizados",
        lead="O cliente pode conhecer produtos, montar o carrinho, revisar itens e avançar no pedido pelo WhatsApp da própria loja, sem depender de mensagens soltas para cada detalhe.",
        section_title="Menos vai e volta para fechar uma venda",
        section_text="O fluxo conversa com o catálogo real da loja. Isso permite orientar o cliente sobre produtos e avançar por quantidade, opções, entrega ou retirada e pagamento de forma mais estruturada.",
        benefits=(
            ("Carrinho dentro da conversa", "O cliente pode adicionar, remover, trocar itens e revisar o carrinho antes de finalizar."),
            ("Entrega ou retirada", "O atendimento respeita as modalidades que a loja habilitou e coleta os dados necessários para o pedido."),
            ("Atendente quando necessário", "Quando a situação pede uma pessoa, o cliente pode solicitar atendimento humano e a loja assume a conversa."),
        ),
        examples=("“Manda dois lanches e uma bebida”", "“Tira o último item”", "“Quero retirar na loja”", "“Quero falar com um atendente”"),
        faq=(
            ("O pedido fica só como uma mensagem?", "Não. O fluxo de carrinho estrutura os itens e os dados do pedido antes da confirmação."),
            ("O cliente pode mudar de ideia durante o pedido?", "Sim. Ele pode revisar o carrinho e pedir alterações antes de concluir."),
            ("Dá para usar Pix?", "Quando o pagamento online está habilitado para a loja, o fluxo pode oferecer Pix online; também há formas de pagamento na entrega ou retirada conforme a configuração."),
        ),
        group="Soluções", related=("agente-whatsapp-delivery", "cardapio-online", "delivery-sem-comissao", "sistema-para-hamburgueria"),
    ),
    "agente-whatsapp-delivery": _page(
        path="agente-whatsapp-delivery/", name="agente_whatsapp_delivery",
        title="Agente de atendimento no WhatsApp para delivery | VemDeDelivery",
        description="Agente no WhatsApp que consulta o catálogo da loja, responde sobre produtos, preços, adicionais, entrega, horários e ajuda a montar pedidos.",
        eyebrow="AGENTE DE ATENDIMENTO NO WHATSAPP",
        h1="Um agente que conhece a operação",
        highlight="da sua loja",
        lead="O agente usa informações cadastradas no VemDeDelivery para responder dúvidas e apoiar o pedido. Ele pode consultar produtos, preços, opções, horários, entrega, retirada e formas de pagamento.",
        section_title="Atendimento útil porque nasce dos dados da loja",
        section_text="A proposta não é colocar um chatbot genérico na conversa. O agente trabalha com o catálogo e com as configurações do estabelecimento, conduzindo o cliente sem prometer uma condição que não esteja habilitada.",
        benefits=(
            ("Respostas sobre o catálogo", "Ajuda com produtos, preços, ingredientes, opções, adicionais e disponibilidade cadastrada."),
            ("Contexto da operação", "Pode orientar sobre horários, áreas e taxas de entrega, retirada e formas de pagamento configuradas."),
            ("Da dúvida ao carrinho", "Quando o cliente decide comprar, o atendimento pode avançar para montar e revisar o pedido no WhatsApp."),
        ),
        examples=("Dúvidas de preço e ingredientes", "Consulta de entrega e retirada", "Escolha de adicionais", "Transferência para atendimento humano"),
        faq=(
            ("O agente inventa preços ou produtos?", "O atendimento é construído para consultar os dados cadastrados da própria loja e validar as opções disponíveis."),
            ("Ele consegue montar pedido?", "Sim. O fluxo de atendimento pode trabalhar com o carrinho, quantidades, opções e finalização."),
            ("Posso assumir a conversa?", "Sim. O fluxo contempla handoff para atendimento humano quando o cliente pede ou quando a situação precisa da loja."),
        ),
        group="Soluções", related=("pedidos-pelo-whatsapp", "cardapio-online", "sistema-para-pizzaria", "sistema-para-pet-shop"),
    ),
    "loja-online-comercio-local": _page(
        path="loja-online-para-comercio-local/", name="loja_online_comercio_local",
        title="Loja online para comércio local e pedidos | VemDeDelivery",
        description="Crie uma loja online para comércio local com catálogo, pedidos, WhatsApp, entrega ou retirada e painel de gestão. Para alimentação, mercados, pet shops e mais.",
        eyebrow="COMÉRCIO LOCAL TAMBÉM VENDE ONLINE",
        h1="Uma loja online simples para o",
        highlight="comércio do bairro",
        lead="O VemDeDelivery não é só para comida. Negócios que trabalham com catálogo, pedido local, retirada ou entrega também podem criar seu canal próprio para vender direto.",
        section_title="Do balcão para um link que você controla",
        section_text="Mercados, mercearias, casas de ração, pet shops, floriculturas, lojas de presentes, cosméticos, papelarias e outros comércios podem organizar produtos em uma vitrine online e usar o WhatsApp para continuar o atendimento.",
        benefits=(
            ("Catálogo por categorias", "Separe produtos de forma clara para o cliente navegar no celular e encontrar o que precisa."),
            ("Operação local", "Configure retirada, entrega, horários e áreas atendidas conforme o funcionamento do seu negócio."),
            ("Relacionamento direto", "Divulgue o próprio link em redes sociais, embalagens, balcão, anúncios e listas de clientes."),
        ),
        examples=("Mercados e mercearias", "Pet shops e casas de ração", "Floriculturas e presentes", "Cosméticos, papelaria e utilidades"),
        faq=(
            ("Preciso trabalhar com comida?", "Não. A plataforma é adequada a diferentes negócios locais que tenham produtos organizáveis em catálogo e uma operação de pedido, retirada ou entrega."),
            ("Consigo usar apenas retirada?", "Sim, desde que a loja configure a modalidade de retirada como disponível."),
            ("Posso divulgar em anúncios?", "Sim. O link da sua loja pode ser usado em campanhas e canais próprios; o acompanhamento de campanhas pode ser configurado separadamente."),
        ),
        group="Soluções", related=("sistema-para-mercado", "sistema-para-pet-shop", "sistema-para-floricultura", "cardapio-online"),
    ),

    # Alimentação
    "sistema-para-pizzaria": _page(
        path="sistema-para-pizzaria/", name="sistema_para_pizzaria",
        title="Sistema para pizzaria: pedidos e WhatsApp | VemDeDelivery",
        description="Sistema para pizzaria com cardápio online, pizza meio a meio, adicionais, entrega, retirada, pedidos e agente no WhatsApp. Sem comissão por pedido.",
        eyebrow="VEMDEDELIVERY PARA PIZZARIAS",
        h1="Cardápio e pedidos online para",
        highlight="pizzaria",
        lead="Apresente sabores, tamanhos e opções em um cardápio próprio, organize a operação de entrega ou retirada e deixe o WhatsApp ajudar o cliente até o pedido.",
        section_title="Uma experiência feita para escolhas que têm detalhes",
        section_text="Pizza costuma exigir tamanho, sabor, combinações e adicionais. O VemDeDelivery já possui recursos para esse tipo de escolha e mantém o pedido estruturado até a finalização.",
        benefits=(("Pizza meio a meio", "Permita combinações compatíveis sem transformar o pedido em uma sequência confusa de mensagens."), ("Adicionais e opções", "Cadastre bordas, extras e outras escolhas disponíveis para cada produto."), ("Entrega organizada", "Configure horários, retirada, regiões e taxas de entrega de acordo com a pizzaria.")),
        examples=("Pizzas tradicionais e especiais", "Tamanhos e bordas", "Combos e bebidas", "Cupons para campanhas"),
        faq=(("O sistema suporta pizza meio a meio?", "Sim. O projeto possui fluxo específico para combinação meio a meio."), ("Posso receber o pedido pelo WhatsApp?", "Sim. O cliente pode conversar, montar carrinho e avançar no pedido pelo WhatsApp da loja."), ("Há comissão por pizza vendida?", "O VemDeDelivery não cobra comissão percentual sobre os pedidos.")),
        group="Alimentação", related=("sistema-para-hamburgueria", "sistema-para-restaurante", "agente-whatsapp-delivery", "delivery-sem-comissao"),
    ),
    "sistema-para-hamburgueria": _page(
        path="sistema-para-hamburgueria/", name="sistema_para_hamburgueria",
        title="Sistema para hamburgueria e pedidos no WhatsApp | VemDeDelivery",
        description="Cardápio online para hamburgueria com adicionais, combos, pedidos no WhatsApp, entrega ou retirada e canal próprio sem comissão por pedido.",
        eyebrow="VEMDEDELIVERY PARA HAMBURGUERIAS",
        h1="Venda seus lanches em um canal",
        highlight="com a sua marca",
        lead="Organize burgers, combos, bebidas e adicionais em um cardápio rápido de navegar. O cliente escolhe, personaliza e pode concluir a conversa pelo WhatsApp da hamburgueria.",
        section_title="Personalização sem perder o controle do pedido",
        section_text="Trocar ingrediente, escolher adicional ou pedir duas unidades não deveria depender de interpretar uma mensagem longa. O catálogo e o carrinho deixam as escolhas mais claras para cliente e loja.",
        benefits=(("Adicionais", "Queijo extra, bacon, molhos e outras opções podem fazer parte da configuração do produto."), ("Combos e bebidas", "Organize categorias para aumentar a visibilidade de acompanhamentos e itens complementares."), ("WhatsApp com carrinho", "O cliente pode pedir do jeito dele e revisar os itens antes de finalizar.")),
        examples=("Hambúrguer artesanal", "Lanches tradicionais", "Combos", "Porções e bebidas"),
        faq=(("Dá para vender adicionais?", "Sim. O catálogo trabalha com opções e adicionais ligados aos produtos."), ("O agente entende alteração no carrinho?", "O fluxo contempla operações como alterar quantidade, remover ou trocar itens, sempre com validações do carrinho."), ("Posso trabalhar com retirada?", "Sim. Entrega e retirada são configuráveis conforme a operação da loja.")),
        group="Alimentação", related=("sistema-para-lanchonete", "sistema-para-pizzaria", "pedidos-pelo-whatsapp", "delivery-sem-comissao"),
    ),
    "sistema-para-restaurante": _page(
        path="sistema-para-restaurante/", name="sistema_para_restaurante",
        title="Sistema de delivery para restaurante | VemDeDelivery",
        description="Sistema de pedidos para restaurante com cardápio online, categorias, adicionais, entrega, retirada, WhatsApp e painel de gestão. Canal próprio sem comissão.",
        eyebrow="VEMDEDELIVERY PARA RESTAURANTES",
        h1="Um canal próprio de pedidos para seu",
        highlight="restaurante",
        lead="Organize pratos, acompanhamentos, bebidas e sobremesas em uma vitrine própria e reduza o caminho entre a divulgação e o pedido.",
        section_title="Cardápio, atendimento e operação no mesmo contexto",
        section_text="O cliente consulta o que a casa oferece e o atendimento usa as mesmas informações de catálogo, horários, entrega e pagamento. Isso ajuda a manter a comunicação coerente.",
        benefits=(("Cardápio por categorias", "Separe entradas, pratos, bebidas, sobremesas e outras linhas de forma fácil de navegar."), ("Horários reais", "Configure os períodos de funcionamento para refletir quando a operação recebe pedidos."), ("Entrega e retirada", "Ative as modalidades que fazem sentido para o restaurante e configure as áreas atendidas.")),
        examples=("Pratos executivos", "À la carte", "Porções e entradas", "Bebidas e sobremesas"),
        faq=(("Posso organizar várias categorias?", "Sim. O catálogo foi construído com categorias e ordenação de produtos."), ("Serve para retirada no balcão?", "Sim. A retirada pode ser disponibilizada junto ou no lugar da entrega."), ("Consigo criar campanhas?", "O projeto possui recursos de cupons/campanhas que podem apoiar ações promocionais.")),
        group="Alimentação", related=("sistema-para-marmitaria", "sistema-para-pizzaria", "cardapio-online", "agente-whatsapp-delivery"),
    ),
    "sistema-para-marmitaria": _page(
        path="sistema-para-marmitaria/", name="sistema_para_marmitaria",
        title="Sistema para marmitaria com pedidos online | VemDeDelivery",
        description="Sistema para marmitaria com cardápio online, tamanhos e opções, entrega ou retirada, pedidos pelo WhatsApp e assinatura sem comissão por pedido.",
        eyebrow="VEMDEDELIVERY PARA MARMITARIAS",
        h1="Pedidos mais simples para sua",
        highlight="marmitaria",
        lead="Mostre o cardápio do dia, tamanhos, acompanhamentos e bebidas em um link fácil de compartilhar com clientes recorrentes, empresas e grupos de WhatsApp.",
        section_title="Agilidade para uma operação que costuma concentrar pedidos",
        section_text="No horário do almoço, perguntas repetidas podem consumir o atendimento. Com catálogo atualizado e agente no WhatsApp, o cliente encontra informações e avança no pedido com menos atrito.",
        benefits=(("Cardápio do dia", "Organize pratos e categorias para destacar o que está disponível em cada momento."), ("Tamanhos e acompanhamentos", "Use opções para representar variações e adicionais do pedido."), ("Clientes recorrentes", "Tenha um link próprio para enviar todos os dias sem depender de montar cardápio em texto.")),
        examples=("Marmitas tradicionais", "Marmitas fitness", "Prato do dia", "Combos semanais e bebidas"),
        faq=(("Posso mudar o cardápio pelo painel?", "Sim. O lojista gerencia produtos, disponibilidade e demais dados da loja pelo painel."), ("Dá para usar para almoço empresarial?", "O catálogo pode ser divulgado para qualquer público; condições comerciais específicas podem ser tratadas diretamente pela loja."), ("Tem retirada?", "Sim, quando habilitada pela loja.")),
        group="Alimentação", related=("sistema-para-restaurante", "sistema-para-lanchonete", "pedidos-pelo-whatsapp", "cardapio-online"),
    ),
    "sistema-para-lanchonete": _page(
        path="sistema-para-lanchonete/", name="sistema_para_lanchonete",
        title="Sistema para lanchonete com cardápio online | VemDeDelivery",
        description="Cardápio online para lanchonete com lanches, porções, bebidas, adicionais, pedidos pelo WhatsApp e delivery sem comissão do VemDeDelivery.",
        eyebrow="VEMDEDELIVERY PARA LANCHONETES",
        h1="Seu cardápio de lanches pronto para",
        highlight="vender direto",
        lead="Deixe lanches, porções, salgados, bebidas e combos fáceis de encontrar e leve o cliente do link ao pedido usando o canal da própria lanchonete.",
        section_title="Menos texto solto, mais escolha organizada",
        section_text="Uma lanchonete costuma ter muitas combinações e itens complementares. Categorias, opções e carrinho ajudam a organizar tudo antes de o pedido chegar à operação.",
        benefits=(("Cardápio completo", "Organize lanches, porções, bebidas, sobremesas e combos em categorias."), ("Personalização", "Cadastre opções e adicionais para produtos que permitem escolhas."), ("Atendimento no WhatsApp", "O agente pode responder dúvidas e apoiar a montagem do pedido.")),
        examples=("Lanches", "Porções", "Salgados", "Bebidas e sobremesas"),
        faq=(("Posso colocar fotos?", "Sim. Os produtos podem ser apresentados com imagem, nome, descrição e preço."), ("Funciona no celular?", "Sim. A experiência é web e responsiva, sem exigir instalação de aplicativo."), ("É só para delivery?", "Não. A loja também pode habilitar retirada.")),
        group="Alimentação", related=("sistema-para-hamburgueria", "sistema-para-padaria", "cardapio-online", "agente-whatsapp-delivery"),
    ),
    "sistema-para-padaria": _page(
        path="sistema-para-padaria/", name="sistema_para_padaria",
        title="Sistema de pedidos online para padaria | VemDeDelivery",
        description="Catálogo online para padaria com pães, salgados, confeitaria, kits, retirada, entrega e pedidos pelo WhatsApp. Canal próprio por assinatura.",
        eyebrow="VEMDEDELIVERY PARA PADARIAS",
        h1="A vitrine da sua padaria também pode estar",
        highlight="no celular",
        lead="Apresente pães, salgados, doces, kits de café e itens do dia em um catálogo próprio para pedidos locais, retirada ou entrega.",
        section_title="Venda além do balcão sem perder a identidade",
        section_text="Produtos de consumo recorrente funcionam bem em um canal direto. O cliente pode consultar o catálogo antes de sair de casa ou fazer o pedido para receber no bairro.",
        benefits=(("Categorias variadas", "Separe pães, frios, salgados, confeitaria, bebidas e kits."), ("Pedidos recorrentes", "Use o mesmo link em redes sociais e listas de clientes todos os dias."), ("Retirada rápida", "Ofereça retirada para clientes que querem adiantar o pedido antes de chegar.")),
        examples=("Pães e frios", "Salgados", "Bolos e doces", "Cestas e kits de café"),
        faq=(("Serve para padaria com muitos produtos?", "Sim. O catálogo é organizado por categorias e permite gerenciar disponibilidade dos itens."), ("Posso vender kits?", "Sim. Kits podem ser cadastrados como produtos próprios, com as informações comerciais definidas pela loja."), ("O WhatsApp ajuda nas dúvidas?", "Sim. O agente pode consultar o catálogo e informações operacionais cadastradas.")),
        group="Alimentação", related=("sistema-para-confeitaria", "sistema-para-lanchonete", "loja-online-comercio-local", "pedidos-pelo-whatsapp"),
    ),
    "sistema-para-confeitaria": _page(
        path="sistema-para-confeitaria/", name="sistema_para_confeitaria",
        title="Sistema de pedidos para confeitaria e doces | VemDeDelivery",
        description="Catálogo online para confeitaria com bolos, doces, kits, opções e pedidos pelo WhatsApp. Divulgue sua própria marca e receba pedidos sem comissão por venda.",
        eyebrow="VEMDEDELIVERY PARA CONFEITARIAS",
        h1="Uma vitrine online para deixar seus doces",
        highlight="falarem por si",
        lead="Fotos, descrições, tamanhos e opções ajudam o cliente a entender melhor o produto antes de chamar. Centralize essa apresentação em um catálogo próprio.",
        section_title="Apresentação importa tanto quanto o atendimento",
        section_text="Confeitaria é visual e frequentemente trabalha com tamanhos, sabores e complementos. Uma vitrine organizada reduz dúvidas básicas e deixa o WhatsApp para o que realmente precisa de conversa.",
        benefits=(("Fotos e descrições", "Destaque acabamento, sabores, tamanhos e características do produto."), ("Opções e adicionais", "Represente variações disponíveis sem precisar escrever todas as combinações manualmente."), ("Canal próprio", "Direcione seguidores e clientes recorrentes para um link com a sua identidade.")),
        examples=("Bolos", "Doces e sobremesas", "Kits para festa", "Caixas para presente"),
        faq=(("Serve para produtos sob encomenda?", "O catálogo pode apresentar produtos e opções; prazos e condições específicas devem ser descritos e confirmados pela loja."), ("Consigo receber pelo WhatsApp?", "Sim. O WhatsApp pode apoiar a conversa e o fluxo de pedido."), ("Posso usar para datas comemorativas?", "Sim. O catálogo e os links próprios são úteis para divulgar linhas sazonais e campanhas.")),
        group="Alimentação", related=("sistema-para-padaria", "sistema-para-acai-e-sorvetes", "cardapio-online", "delivery-sem-comissao"),
    ),
    "sistema-para-acai-e-sorvetes": _page(
        path="sistema-para-acai-e-sorvetes/", name="sistema_para_acai_sorvetes",
        title="Sistema para açaí e sorveteria com adicionais | VemDeDelivery",
        description="Cardápio online para açaí e sorveteria com tamanhos, adicionais, complementos, entrega, retirada e pedidos pelo WhatsApp.",
        eyebrow="VEMDEDELIVERY PARA AÇAÍ E SORVETES",
        h1="Tamanhos e adicionais organizados para",
        highlight="facilitar o pedido",
        lead="Apresente copos, potes, sabores e complementos de forma estruturada para o cliente montar o pedido com menos mensagens de ida e volta.",
        section_title="Quando as combinações são parte do produto",
        section_text="Açaí e sorvete dependem de escolhas: tamanho, sabor, cobertura, frutas e extras. O catálogo pode representar essas opções e levar o resultado para o carrinho.",
        benefits=(("Tamanhos e opções", "Estruture variações para o cliente saber o que pode escolher."), ("Adicionais", "Cadastre complementos e extras disponíveis para cada produto."), ("Entrega ou retirada", "Defina a operação local e as regiões atendidas pela loja.")),
        examples=("Açaí no copo", "Açaí no pote", "Sorvetes", "Complementos e bebidas"),
        faq=(("Dá para cobrar adicional?", "Sim. O catálogo trabalha com opções/adicionais e seus valores quando configurados."), ("Posso limitar o que está disponível?", "Produtos e opções possuem controles de disponibilidade na operação."), ("O cliente consegue revisar tudo?", "Sim. O carrinho permite revisar os itens antes da conclusão.")),
        group="Alimentação", related=("sistema-para-confeitaria", "sistema-para-lanchonete", "pedidos-pelo-whatsapp", "cardapio-online"),
    ),
    "sistema-para-comida-japonesa": _page(
        path="sistema-para-comida-japonesa/", name="sistema_para_comida_japonesa",
        title="Sistema para delivery de comida japonesa | VemDeDelivery",
        description="Cardápio online para sushi e comida japonesa com combinados, porções, adicionais, pedidos pelo WhatsApp, entrega e retirada.",
        eyebrow="VEMDEDELIVERY PARA COMIDA JAPONESA",
        h1="Combinados e opções em um cardápio",
        highlight="fácil de escolher",
        lead="Organize sushis, temakis, combinados, porções e bebidas com fotos e descrições para o cliente comparar opções e montar o pedido no próprio canal da loja.",
        section_title="Clareza para cardápios com muitos itens",
        section_text="Nomes, quantidades e composições precisam estar visíveis para evitar dúvida. Um catálogo organizado ajuda o cliente a escolher e reduz perguntas repetidas no atendimento.",
        benefits=(("Descrições completas", "Explique composição e quantidade de peças em cada produto."), ("Categorias", "Separe combinados, temakis, hot rolls, bebidas e demais linhas."), ("WhatsApp integrado ao contexto", "O agente consulta o catálogo para responder dúvidas antes de montar o pedido.")),
        examples=("Combinados", "Temakis", "Porções", "Bebidas e sobremesas"),
        faq=(("Posso informar quantidade de peças?", "Sim. A descrição do produto pode detalhar composição, quantidades e outras informações úteis."), ("Dá para trabalhar com adicionais?", "Sim, quando o produto possui opções configuradas."), ("Posso oferecer retirada?", "Sim. A modalidade pode ser habilitada pela loja.")),
        group="Alimentação", related=("sistema-para-restaurante", "sistema-para-lanchonete", "agente-whatsapp-delivery", "delivery-sem-comissao"),
    ),
    "sistema-para-adega-e-bebidas": _page(
        path="sistema-para-adega-e-bebidas/", name="sistema_para_adega_bebidas",
        title="Sistema de pedidos para adega e loja de bebidas | VemDeDelivery",
        description="Catálogo online para adega e bebidas com categorias, combos, entrega local, retirada e pedidos pelo WhatsApp em um canal próprio.",
        eyebrow="VEMDEDELIVERY PARA ADEGAS E BEBIDAS",
        h1="Seu catálogo de bebidas pronto para",
        highlight="pedido local",
        lead="Organize bebidas, refrigerantes, água, gelo, snacks e combos em um catálogo próprio, com horários e regiões de entrega configurados pela loja.",
        section_title="Encontre rápido, peça rápido",
        section_text="Clientes de conveniência valorizam agilidade. Categorias e busca visual pelo catálogo ajudam a reduzir perguntas de preço e disponibilidade antes do pedido.",
        benefits=(("Categorias claras", "Separe bebidas e itens complementares para facilitar a navegação."), ("Combos", "Cadastre combinações como produtos para destacar ofertas da loja."), ("Horários e entrega", "Mantenha a operação alinhada ao período e às regiões em que a loja atende.")),
        examples=("Bebidas não alcoólicas", "Combos", "Água e gelo", "Snacks e conveniência"),
        faq=(("Posso definir horários?", "Sim. A loja configura seus períodos de funcionamento."), ("Consigo separar por categorias?", "Sim. O catálogo foi pensado para organizar produtos em categorias."), ("Há entrega por região?", "Sim. A operação pode usar áreas e taxas de entrega configuradas pela loja.")),
        group="Alimentação", related=("sistema-para-conveniencia", "sistema-para-mercado", "cardapio-online", "pedidos-pelo-whatsapp"),
    ),

    # Varejo e comércio local
    "sistema-para-mercado": _page(
        path="sistema-para-mercado/", name="sistema_para_mercado",
        title="Sistema de pedidos online para mercado | VemDeDelivery",
        description="Catálogo e pedidos online para mercado com categorias, entrega local, retirada, WhatsApp e painel. Crie um canal próprio sem comissão por pedido.",
        eyebrow="VEMDEDELIVERY PARA MERCADOS",
        h1="Um canal direto para pedidos do seu",
        highlight="mercado",
        lead="Leve itens de compra recorrente para um catálogo próprio e facilite pedidos locais com categorias, retirada ou entrega e atendimento pelo WhatsApp.",
        section_title="O cliente já compra perto. Falta facilitar o pedido online.",
        section_text="O VemDeDelivery ajuda mercados de bairro a criar um ponto digital próprio sem depender apenas de mensagens com listas extensas de produtos.",
        benefits=(("Categorias de compra", "Organize mercearia, bebidas, higiene, limpeza, hortifruti e outras seções."), ("Entrega no bairro", "Configure áreas atendidas e taxas conforme a operação local."), ("Canal de relacionamento", "Use o mesmo link em campanhas, redes sociais e WhatsApp com clientes recorrentes.")),
        examples=("Itens de mercearia", "Bebidas", "Higiene e limpeza", "Hortifruti e conveniência"),
        faq=(("Serve para mercado de bairro?", "Sim. A proposta é especialmente adequada a comércio local com retirada ou entrega."), ("Posso ter muitas categorias?", "Sim. O catálogo trabalha com organização por categorias."), ("O cliente pode tirar dúvidas no WhatsApp?", "Sim. O agente pode consultar produtos e dados operacionais cadastrados.")),
        group="Varejo local", related=("sistema-para-mercearia", "sistema-para-mercadinho", "sistema-para-hortifruti", "loja-online-comercio-local"),
    ),
    "sistema-para-mercearia": _page(
        path="sistema-para-mercearia/", name="sistema_para_mercearia",
        title="Sistema de pedidos para mercearia | VemDeDelivery",
        description="Crie um catálogo online para mercearia com produtos por categoria, entrega ou retirada e pedidos pelo WhatsApp. Canal próprio por assinatura.",
        eyebrow="VEMDEDELIVERY PARA MERCEARIAS",
        h1="Sua mercearia em um link fácil de",
        highlight="mandar para o cliente",
        lead="Troque listas improvisadas por um catálogo que o cliente pode abrir sempre que precisar de itens do dia a dia e continuar o pedido no WhatsApp.",
        section_title="Praticidade para compras pequenas e recorrentes",
        section_text="Mercearias vivem da proximidade. Um canal online ajuda a manter essa relação, dando ao cliente uma forma rápida de consultar itens e pedir sem precisar perguntar preço por preço.",
        benefits=(("Catálogo simples de consultar", "Organize produtos essenciais em categorias e mantenha preços e descrições centralizados."), ("Retirada ou entrega", "Atenda quem quer passar para buscar e quem prefere receber."), ("WhatsApp da própria loja", "A conversa continua no número do estabelecimento, preservando o relacionamento direto.")),
        examples=("Alimentos básicos", "Bebidas", "Limpeza", "Itens de conveniência"),
        faq=(("É necessário cadastrar tudo de uma vez?", "A loja pode evoluir o catálogo gradualmente e também existe serviço opcional de implantação/cadastro contratado à parte."), ("Posso atualizar preços?", "Sim. Os produtos são gerenciados no painel da loja."), ("Tem comissão por venda?", "O VemDeDelivery não cobra comissão percentual sobre o pedido.")),
        group="Varejo local", related=("sistema-para-mercadinho", "sistema-para-mercado", "sistema-para-conveniencia", "delivery-sem-comissao"),
    ),
    "sistema-para-mercadinho": _page(
        path="sistema-para-mercadinho/", name="sistema_para_mercadinho",
        title="Sistema para mercadinho de bairro | VemDeDelivery",
        description="Sistema para mercadinho com catálogo online, pedidos por WhatsApp, retirada, entrega local e canal próprio sem comissão sobre os pedidos.",
        eyebrow="VEMDEDELIVERY PARA MERCADINHOS",
        h1="O mercadinho do bairro também pode",
        highlight="vender online",
        lead="Crie um link próprio para os clientes próximos consultarem produtos, pedirem itens de reposição rápida e escolherem entrega ou retirada.",
        section_title="Conveniência digital para quem já conhece sua loja",
        section_text="Em vez de o cliente mandar uma lista e esperar alguém confirmar item por item, o catálogo apresenta parte relevante do mix e organiza melhor o início do pedido.",
        benefits=(("Compra rápida", "Destaque os itens mais pedidos e as categorias que mais giram no dia a dia."), ("Bairro e proximidade", "Defina áreas de entrega compatíveis com a operação do mercadinho."), ("Divulgação simples", "Use o link em ímãs, panfletos, embalagens, redes sociais e mensagens.")),
        examples=("Reposição do dia a dia", "Bebidas geladas", "Higiene", "Snacks e utilidades"),
        faq=(("É diferente de um marketplace?", "O VemDeDelivery cria um canal próprio da loja, com sua marca e relacionamento direto."), ("Posso atender só meu bairro?", "Sim. As áreas de entrega são configuradas de acordo com a operação da loja."), ("O cliente instala app?", "Não. O catálogo abre por link no navegador.")),
        group="Varejo local", related=("sistema-para-mercearia", "sistema-para-mercado", "sistema-para-conveniencia", "cardapio-online"),
    ),
    "sistema-para-hortifruti": _page(
        path="sistema-para-hortifruti/", name="sistema_para_hortifruti",
        title="Sistema de pedidos online para hortifruti | VemDeDelivery",
        description="Catálogo online para hortifruti com frutas, verduras, legumes, kits, entrega ou retirada e pedidos pelo WhatsApp.",
        eyebrow="VEMDEDELIVERY PARA HORTIFRUTIS",
        h1="Frutas, verduras e kits em uma vitrine",
        highlight="fácil de pedir",
        lead="Organize o mix do dia em categorias e ofereça um canal direto para clientes que querem praticidade na compra de produtos frescos.",
        section_title="Atualização e proximidade fazem diferença",
        section_text="Hortifruti muda bastante por disponibilidade. O painel permite gerenciar o catálogo e destacar o que está disponível, enquanto o WhatsApp ajuda com dúvidas específicas.",
        benefits=(("Categorias naturais", "Separe frutas, verduras, legumes, ovos, temperos e outros grupos."), ("Kits e cestas", "Cadastre combinações prontas para facilitar compras recorrentes."), ("Atendimento local", "Configure entrega e retirada de acordo com a área de atuação.")),
        examples=("Frutas", "Verduras e legumes", "Kits semanais", "Temperos e complementos"),
        faq=(("Posso marcar item indisponível?", "Sim. A disponibilidade do produto faz parte da gestão do catálogo."), ("Dá para vender cestas?", "Sim. Cestas e kits podem ser cadastrados como produtos com descrição própria."), ("O agente sabe a área de entrega?", "Ele pode consultar as informações de entrega configuradas na loja.")),
        group="Varejo local", related=("sistema-para-mercado", "sistema-para-mercearia", "cardapio-online", "agente-whatsapp-delivery"),
    ),
    "sistema-para-acougue": _page(
        path="sistema-para-acougue/", name="sistema_para_acougue",
        title="Sistema de pedidos online para açougue | VemDeDelivery",
        description="Catálogo online para açougue com cortes, kits, acompanhamentos, entrega, retirada e pedidos pelo WhatsApp em canal próprio.",
        eyebrow="VEMDEDELIVERY PARA AÇOUGUES",
        h1="Mostre seus cortes e kits antes mesmo do",
        highlight="cliente chamar",
        lead="Apresente cortes, kits, temperados, congelados e complementos em um catálogo próprio, reduzindo perguntas básicas e facilitando pedidos locais.",
        section_title="Mais contexto para uma compra que costuma gerar perguntas",
        section_text="Descrição e apresentação ajudam o cliente a identificar o corte ou kit que procura. Casos específicos continuam podendo ser tratados no WhatsApp com a equipe.",
        benefits=(("Cortes e categorias", "Organize bovinos, suínos, aves, kits e linhas especiais."), ("Kits", "Crie produtos para churrasco, semana ou ocasiões específicas."), ("Atendimento híbrido", "O catálogo resolve o básico e o atendente pode assumir dúvidas que exigem orientação humana.")),
        examples=("Cortes", "Kits para churrasco", "Temperados", "Congelados e complementos"),
        faq=(("Posso colocar observações no produto?", "Sim. Descrições ajudam a explicar composição e condições; necessidades específicas podem ser confirmadas com a loja."), ("Serve para retirada?", "Sim. A loja pode habilitar retirada."), ("Posso falar com o cliente no WhatsApp?", "Sim. O número da própria loja permanece no centro do atendimento.")),
        group="Varejo local", related=("sistema-para-mercado", "sistema-para-hortifruti", "pedidos-pelo-whatsapp", "loja-online-comercio-local"),
    ),
    "sistema-para-conveniencia": _page(
        path="sistema-para-conveniencia/", name="sistema_para_conveniencia",
        title="Sistema de pedidos para loja de conveniência | VemDeDelivery",
        description="Catálogo online para conveniência com bebidas, snacks, itens rápidos, entrega local, retirada e pedidos pelo WhatsApp.",
        eyebrow="VEMDEDELIVERY PARA CONVENIÊNCIAS",
        h1="Conveniência também significa pedir em",
        highlight="poucos passos",
        lead="Organize os itens que mais giram, divulgue um único link e facilite pedidos rápidos para clientes próximos da sua loja.",
        section_title="Agilidade é parte do produto",
        section_text="Quem compra em uma conveniência normalmente quer resolver rápido. Um catálogo simples, horários claros e atendimento pelo WhatsApp reduzem etapas desnecessárias.",
        benefits=(("Itens de giro rápido", "Destaque bebidas, snacks, gelo, higiene e outros produtos de conveniência."), ("Horário configurado", "Mantenha o canal alinhado ao período real de atendimento."), ("Entrega de proximidade", "Defina as áreas e taxas compatíveis com sua operação.")),
        examples=("Bebidas", "Snacks", "Gelo", "Higiene e utilidades"),
        faq=(("Posso ter entrega e retirada?", "Sim. As duas modalidades podem ser configuradas conforme a loja."), ("Dá para divulgar por QR Code?", "Sim. O endereço da loja pode ser transformado em QR Code e usado em materiais físicos."), ("Tem agente no WhatsApp?", "Sim. O plano inclui o agente de atendimento da plataforma.")),
        group="Varejo local", related=("sistema-para-mercadinho", "sistema-para-adega-e-bebidas", "agente-whatsapp-delivery", "cardapio-online"),
    ),
    "sistema-para-pet-shop": _page(
        path="sistema-para-pet-shop/", name="sistema_para_pet_shop",
        title="Sistema de pedidos online para pet shop | VemDeDelivery",
        description="Catálogo online para pet shop com rações, petiscos, higiene, acessórios, entrega ou retirada e pedidos pelo WhatsApp.",
        eyebrow="VEMDEDELIVERY PARA PET SHOPS",
        h1="Ração, petiscos e acessórios em um catálogo",
        highlight="pronto para pedir",
        lead="Facilite a recompra de itens recorrentes e organize produtos por tipo, porte ou linha em um canal próprio do pet shop.",
        section_title="Recompra recorrente combina com canal direto",
        section_text="Quem compra a mesma ração ou areia com frequência não deveria precisar perguntar o preço toda vez. O catálogo ajuda o cliente a encontrar o produto e seguir para o pedido.",
        benefits=(("Produtos recorrentes", "Destaque rações, areias, tapetes, petiscos e itens de higiene."), ("Categorias", "Organize por espécie, linha ou finalidade de forma compreensível para o cliente."), ("Entrega local", "Configure as regiões atendidas e mantenha o WhatsApp para dúvidas específicas.")),
        examples=("Rações", "Petiscos", "Higiene", "Acessórios"),
        faq=(("Serve para produtos de cachorro e gato?", "Sim. Você pode organizar categorias e produtos conforme o mix do pet shop."), ("Posso trabalhar com entrega de saco de ração?", "O sistema permite configurar entrega; a loja define sua política operacional e área atendida."), ("Dá para usar para banho e tosa?", "O foco atual da plataforma é catálogo e pedidos de produtos; agendamento de serviços não é o fluxo principal.")),
        group="Varejo local", related=("sistema-para-casa-de-racao", "loja-online-comercio-local", "pedidos-pelo-whatsapp", "delivery-sem-comissao"),
    ),
    "sistema-para-casa-de-racao": _page(
        path="sistema-para-casa-de-racao/", name="sistema_para_casa_racao",
        title="Sistema de pedidos para casa de ração | VemDeDelivery",
        description="Catálogo online para casa de ração com rações, sacarias, petiscos, higiene e entrega local. Receba pedidos pelo WhatsApp sem comissão do VemDeDelivery.",
        eyebrow="VEMDEDELIVERY PARA CASAS DE RAÇÃO",
        h1="Facilite a recompra de ração com um",
        highlight="canal próprio",
        lead="Apresente marcas, linhas e tamanhos de embalagem em um catálogo que o cliente pode consultar antes de pedir entrega ou retirada.",
        section_title="Quando o cliente já sabe o que compra, o caminho deve ser curto",
        section_text="Casas de ração têm produtos recorrentes e clientes de proximidade. Um link próprio ajuda a transformar essa recorrência em pedidos mais organizados.",
        benefits=(("Marcas e embalagens", "Use nome, descrição e preço para diferenciar linhas e tamanhos de produtos."), ("Pedidos pesados", "A loja define suas áreas e condições de entrega de acordo com a capacidade operacional."), ("WhatsApp para confirmação", "O atendimento permanece próximo para dúvidas de disponibilidade ou substituição.")),
        examples=("Ração seca", "Areias e granulados", "Petiscos", "Higiene animal"),
        faq=(("Posso cadastrar várias marcas?", "Sim. O catálogo não limita a loja a uma única marca ou categoria comercial."), ("Consigo limitar a região de entrega?", "Sim. As zonas de entrega fazem parte da configuração do tenant."), ("Tem mensalidade ou comissão?", "Há assinatura; o VemDeDelivery não aplica comissão percentual sobre os pedidos.")),
        group="Varejo local", related=("sistema-para-pet-shop", "sistema-para-mercadinho", "cardapio-online", "agente-whatsapp-delivery"),
    ),
    "sistema-para-floricultura": _page(
        path="sistema-para-floricultura/", name="sistema_para_floricultura",
        title="Sistema de pedidos online para floricultura | VemDeDelivery",
        description="Catálogo online para floricultura com buquês, arranjos, presentes, entrega local, retirada e atendimento pelo WhatsApp.",
        eyebrow="VEMDEDELIVERY PARA FLORICULTURAS",
        h1="Flores e presentes em uma vitrine que",
        highlight="valoriza a escolha",
        lead="Mostre buquês, arranjos, cestas e presentes com fotos e descrições para o cliente escolher antes de conversar sobre detalhes da entrega.",
        section_title="Um produto visual merece uma apresentação visual",
        section_text="A vitrine online ajuda o cliente a comparar estilos e faixas de preço. O WhatsApp continua disponível para cartões, observações e situações que precisam de atendimento humano.",
        benefits=(("Fotos em destaque", "Apresente cada composição de forma mais clara do que em uma lista de mensagens."), ("Categorias por ocasião", "Organize flores, cestas, presentes ou linhas sazonais."), ("Entrega local", "Configure as regiões em que a loja consegue entregar.")),
        examples=("Buquês", "Arranjos", "Cestas", "Presentes e datas especiais"),
        faq=(("Posso usar para Dia das Mães e outras datas?", "Sim. O catálogo pode ser atualizado com linhas sazonais e campanhas."), ("Dá para conversar sobre cartão e observação?", "Sim. Detalhes especiais podem continuar sendo tratados no WhatsApp da loja."), ("Posso oferecer retirada?", "Sim, se a floricultura habilitar essa modalidade.")),
        group="Varejo local", related=("sistema-para-loja-de-presentes", "loja-online-comercio-local", "cardapio-online", "pedidos-pelo-whatsapp"),
    ),
    "sistema-para-loja-de-presentes": _page(
        path="sistema-para-loja-de-presentes/", name="sistema_para_loja_presentes",
        title="Sistema de pedidos para loja de presentes | VemDeDelivery",
        description="Catálogo online para loja de presentes com categorias, kits, entrega ou retirada e atendimento pelo WhatsApp em um canal próprio.",
        eyebrow="VEMDEDELIVERY PARA LOJAS DE PRESENTES",
        h1="Um catálogo online para ajudar o cliente a",
        highlight="escolher o presente",
        lead="Organize opções por ocasião, categoria ou faixa de produto e leve o cliente da descoberta ao pedido sem depender só de fotos enviadas manualmente.",
        section_title="Mais opções visíveis, menos catálogo improvisado no chat",
        section_text="Quando cada cliente pede 'me manda o que você tem', a equipe repete o mesmo trabalho. Um catálogo centraliza a vitrine e deixa a conversa para detalhes finais.",
        benefits=(("Vitrine permanente", "Mantenha produtos disponíveis em um endereço que pode ser compartilhado a qualquer momento."), ("Kits", "Cadastre combinações prontas como produtos próprios."), ("Atendimento humano quando precisa", "Personalizações específicas podem ser concluídas diretamente com a loja.")),
        examples=("Kits", "Presentes corporativos", "Datas comemorativas", "Itens de decoração"),
        faq=(("Posso criar categorias por ocasião?", "Sim. As categorias são administradas pela loja e podem refletir a organização que fizer sentido."), ("O cliente pode retirar?", "Sim, se a loja disponibilizar retirada."), ("Preciso pagar por venda?", "O VemDeDelivery trabalha com assinatura e não cobra comissão percentual sobre pedidos.")),
        group="Varejo local", related=("sistema-para-floricultura", "sistema-para-cosmeticos", "loja-online-comercio-local", "delivery-sem-comissao"),
    ),
    "sistema-para-cosmeticos": _page(
        path="sistema-para-cosmeticos/", name="sistema_para_cosmeticos",
        title="Sistema de pedidos para loja de cosméticos | VemDeDelivery",
        description="Catálogo online para cosméticos e perfumaria com categorias, kits, retirada, entrega local e pedidos pelo WhatsApp.",
        eyebrow="VEMDEDELIVERY PARA COSMÉTICOS E PERFUMARIA",
        h1="Produtos de beleza em um catálogo",
        highlight="com a sua marca",
        lead="Apresente linhas, fragrâncias, cuidados e kits em uma vitrine própria e use o WhatsApp para orientar o cliente quando ele precisar de ajuda.",
        section_title="Descoberta no catálogo, conversa quando agrega valor",
        section_text="Uma boa organização por linha e finalidade reduz o volume de fotos enviadas manualmente. O atendimento pode se concentrar em recomendação e disponibilidade.",
        benefits=(("Categorias e linhas", "Organize maquiagem, cabelo, pele, perfumaria e kits."), ("Fotos e descrição", "Mostre o produto de forma consistente para facilitar comparação."), ("Canal direto", "Leve seguidores e clientes recorrentes para o próprio link da loja.")),
        examples=("Maquiagem", "Cuidados com cabelo", "Skincare", "Perfumes e kits"),
        faq=(("Serve para perfumaria?", "Sim. Perfumes e cosméticos podem ser organizados em categorias e produtos."), ("Posso cadastrar kits?", "Sim. Kits podem ser produtos próprios no catálogo."), ("Dá para atender pelo WhatsApp?", "Sim. O WhatsApp é um dos canais centrais da solução.")),
        group="Varejo local", related=("sistema-para-loja-de-presentes", "sistema-para-roupas-e-acessorios", "cardapio-online", "agente-whatsapp-delivery"),
    ),
    "sistema-para-papelaria": _page(
        path="sistema-para-papelaria/", name="sistema_para_papelaria",
        title="Sistema de pedidos online para papelaria | VemDeDelivery",
        description="Catálogo online para papelaria com materiais escolares, escritório, presentes, retirada, entrega local e pedidos pelo WhatsApp.",
        eyebrow="VEMDEDELIVERY PARA PAPELARIAS",
        h1="Material escolar e de escritório em um",
        highlight="catálogo fácil de consultar",
        lead="Organize cadernos, canetas, materiais, presentes e itens de escritório para clientes que querem consultar antes de ir à loja ou pedir entrega.",
        section_title="Uma vitrine útil o ano inteiro",
        section_text="Volta às aulas é um pico, mas o catálogo pode continuar funcionando para reposições, escritório, presentes e compras rápidas ao longo do ano.",
        benefits=(("Categorias", "Separe escolar, escritório, escrita, arte, presentes e outras linhas."), ("Campanhas sazonais", "Destaque produtos e kits em períodos de maior procura."), ("Retirada", "Permita que o cliente deixe o pedido encaminhado antes de passar na loja.")),
        examples=("Material escolar", "Escritório", "Arte", "Presentes e organização"),
        faq=(("Posso usar na volta às aulas?", "Sim. O catálogo pode ser atualizado e divulgado em campanhas sazonais."), ("Dá para vender kits escolares?", "Sim. Kits podem ser cadastrados como produtos."), ("É necessário app?", "Não. O cliente acessa pelo navegador.")),
        group="Varejo local", related=("sistema-para-loja-de-presentes", "sistema-para-utilidades", "loja-online-comercio-local", "cardapio-online"),
    ),
    "sistema-para-roupas-e-acessorios": _page(
        path="sistema-para-roupas-e-acessorios/", name="sistema_para_roupas_acessorios",
        title="Catálogo online para loja de roupas e acessórios | VemDeDelivery",
        description="Crie um catálogo online para loja de roupas e acessórios, com fotos, opções, retirada, entrega local e atendimento pelo WhatsApp.",
        eyebrow="VEMDEDELIVERY PARA MODA LOCAL",
        h1="Sua coleção em um catálogo próprio para",
        highlight="vender no bairro",
        lead="Mostre peças e acessórios em um link da sua loja e use o WhatsApp para confirmar variações, disponibilidade e detalhes antes do pedido.",
        section_title="Do Instagram para uma vitrine mais organizada",
        section_text="Redes sociais atraem atenção, mas um catálogo ajuda a reunir as peças disponíveis em um lugar só. Para operações locais, retirada e entrega podem completar a experiência.",
        benefits=(("Fotos e descrição", "Centralize informações essenciais de cada peça ou acessório."), ("Opções", "Use opções do produto para representar escolhas compatíveis com seu catálogo."), ("WhatsApp da loja", "Mantenha a conversa direta para orientação e confirmação de detalhes.")),
        examples=("Roupas", "Acessórios", "Bolsas", "Coleções e kits"),
        faq=(("O VemDeDelivery substitui um e-commerce nacional?", "O foco é comércio local, catálogo, pedidos, retirada/entrega e WhatsApp; operações complexas de frete nacional não são o foco principal."), ("Posso divulgar no Instagram?", "Sim. O link pode ser usado na bio, stories, anúncios e mensagens."), ("Consigo mostrar opções?", "Sim. Produtos podem trabalhar com opções configuradas pela loja.")),
        group="Varejo local", related=("sistema-para-cosmeticos", "sistema-para-loja-de-presentes", "loja-online-comercio-local", "pedidos-pelo-whatsapp"),
    ),
    "sistema-para-utilidades": _page(
        path="sistema-para-utilidades/", name="sistema_para_utilidades",
        title="Catálogo online para loja de utilidades | VemDeDelivery",
        description="Sistema de catálogo e pedidos para loja de utilidades, variedades e comércio local, com retirada, entrega e WhatsApp.",
        eyebrow="VEMDEDELIVERY PARA UTILIDADES E VARIEDADES",
        h1="Muitos produtos, um único link para",
        highlight="organizar a vitrine",
        lead="Use categorias para apresentar itens de casa, cozinha, organização, limpeza e variedades sem depender de enviar fotos uma a uma no WhatsApp.",
        section_title="Organização é o que transforma variedade em catálogo",
        section_text="Lojas de utilidades costumam ter um mix amplo. Separar produtos por categorias e destacar itens de maior procura ajuda o cliente a navegar sem se perder.",
        benefits=(("Categorias", "Crie divisões que acompanhem o mix real da sua loja."), ("Vitrine própria", "Compartilhe o link da sua marca em qualquer canal."), ("Operação local", "Use retirada ou entrega nas regiões que a loja consegue atender.")),
        examples=("Casa e cozinha", "Organização", "Limpeza", "Variedades"),
        faq=(("Preciso cadastrar o estoque inteiro?", "Não. Você pode começar pelos itens de maior giro e ampliar o catálogo gradualmente."), ("Existe serviço para ajudar no cadastro?", "Sim. A operação comercial prevê serviços opcionais de implantação/cadastro cobrados à parte da assinatura."), ("Posso receber pedidos pelo WhatsApp?", "Sim. O WhatsApp faz parte da experiência do VemDeDelivery.")),
        group="Varejo local", related=("sistema-para-papelaria", "sistema-para-mercadinho", "loja-online-comercio-local", "cardapio-online"),
    ),
}


PAGE_GROUP_ORDER = ("Soluções", "Alimentação", "Varejo local")


def grouped_pages():
    return [
        (group, [(key, page) for key, page in MARKETING_PAGES.items() if page["group"] == group])
        for group in PAGE_GROUP_ORDER
    ]
